#!/usr/bin/env python3
"""GRC Batch 7 — push to 300. More NIST + ISO + CIS + SOC2 + PCI."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== NIST BATCH 3 (25) =====================
N7=[
ctrl("nist-ac-8","NIST 800-53","Access Control","AC","AC-8","System Use Notification","Display system use notification before granting access with privacy/security warnings.",["Display login banner","Include authorized use statement","Warn of monitoring","Require acknowledgment"],["Banner configuration","Banner text","Acknowledgment records"],["Unauthorized use claims","Legal liability"],"medium",{"iso_27001":["A.5.10"],"cis_v8":["N/A"]},["AC-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-10","NIST 800-53","Access Control","AC","AC-10","Concurrent Session Control","Limit the number of concurrent sessions for each account.",["Set max concurrent sessions","Alert on violations","Terminate oldest session on limit","Exempt service accounts with justification"],["Session limit configuration","Violation alerts","Exception documentation"],["Session hijacking","Resource exhaustion"],"medium",{"iso_27001":["A.8.5"],"cis_v8":["N/A"]},["AC-2","AC-12"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-12","NIST 800-53","Access Control","AC","AC-12","Session Termination","Automatically terminate a user session after defined conditions.",["Terminate after inactivity timeout","End session on logout","Clear session data","Log session terminations"],["Timeout configuration","Session logs","Termination events"],["Unauthorized access via abandoned sessions"],"medium",{"iso_27001":["A.8.5"],"cis_v8":["N/A"]},["AC-11","AC-10"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-20","NIST 800-53","Access Control","AC","AC-20","Use of External Systems","Establish terms for authorized individuals to access the system from external systems.",["Define approved external systems","Require security controls on external devices","Limit data accessible externally","Monitor external access"],["External access policy","Approved device list","Monitoring records"],["Data exposure via uncontrolled devices"],"high",{"iso_27001":["A.6.7"],"cis_v8":["N/A"]},["AC-17","AC-19"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-at-3","NIST 800-53","Awareness and Training","AT","AT-3","Role-Based Training","Provide role-based security training to personnel with assigned security roles.",["Train admins on secure configuration","Train developers on secure coding","Train IR team on procedures","Update training on role changes"],["Role-based training curriculum","Completion records","Skill assessments"],["Inadequate skills for security roles"],"high",{"iso_27001":["A.6.3"],"cis_v8":["14.9"]},["AT-2","IR-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-4","NIST 800-53","Audit and Accountability","AU","AU-4","Audit Log Storage Capacity","Allocate sufficient audit log storage capacity to prevent loss.",["Size storage for retention period","Implement log rotation","Alert on capacity thresholds","Archive old logs"],["Storage capacity planning","Rotation configuration","Capacity alerts","Archive procedures"],["Log loss","Compliance gaps"],"medium",{"iso_27001":["A.8.15"],"cis_v8":["8.3"]},["AU-2","AU-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-5","NIST 800-53","Audit and Accountability","AU","AU-5","Response to Audit Logging Process Failures","Alert on audit logging failures and take defined actions.",["Alert when logging fails","Switch to backup logging","Shut down system if logging critical","Investigate failures immediately"],["Failure alert configuration","Backup logging","Response procedures"],["Unlogged activity during failures"],"high",{"iso_27001":["A.8.15"],"cis_v8":["8.2"]},["AU-2","AU-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-8","NIST 800-53","Audit and Accountability","AU","AU-8","Time Stamps","Use internal system clocks to generate time stamps for audit records.",["Synchronize to authoritative NTP source","Use UTC for all logs","Monitor for clock drift","Alert on sync failures"],["NTP configuration","Time source documentation","Drift monitoring"],["Inaccurate timestamps","Forensic challenges"],"medium",{"iso_27001":["A.8.17"],"cis_v8":["8.4"]},["AU-3","AU-12"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ca-8","NIST 800-53","Assessment, Authorization, and Monitoring","CA","CA-8","Penetration Testing","Conduct penetration testing on the system at defined frequency.",["Annual external pentest","Internal pentest semi-annually","Remediate findings within SLA","Retest after remediation"],["Pentest reports","Scope documents","Remediation records","Retest results"],["Unknown exploitable vulnerabilities"],"high",{"iso_27001":["A.5.35","A.8.8"],"cis_v8":["18.1","18.2"]},["CA-2","RA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-11","NIST 800-53","Configuration Management","CM","CM-11","User-Installed Software","Establish policy governing the installation of software by users.",["Define approved software list","Block unauthorized installations","Monitor for policy violations","Implement application whitelisting"],["Software policy","Whitelist configuration","Violation reports"],["Malware installation","Unauthorized tools","License violations"],"high",{"iso_27001":["A.8.9"],"cis_v8":["2.3","2.5"]},["CM-7","CM-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cp-3","NIST 800-53","Contingency Planning","CP","CP-3","Contingency Training","Provide contingency training to personnel consistent with assigned roles.",["Train on contingency procedures","Include tabletop exercises","Practice recovery procedures","Update training on plan changes"],["Training records","Exercise results","Skill assessments"],["Ineffective recovery","Untrained personnel"],"medium",{"iso_27001":["A.5.29"],"cis_v8":["N/A"]},["CP-2","CP-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cp-10","NIST 800-53","Contingency Planning","CP","CP-10","System Recovery and Reconstitution","Provide for the recovery and reconstitution of the system to a known state.",["Define recovery procedures","Maintain recovery media","Test reconstitution","Document known-good state"],["Recovery procedures","Recovery media","Test results","Baseline documentation"],["Extended outages","Incomplete recovery"],"high",{"iso_27001":["A.5.30"],"cis_v8":["11.1"]},["CP-2","CP-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ia-6","NIST 800-53","Identification and Authentication","IA","IA-6","Authentication Feedback","Obscure feedback of authentication information during the authentication process.",["Mask password input","Don't reveal which field is wrong","Limit error information","Use generic error messages"],["Login page configuration","Error message review","Authentication UI"],["Credential enumeration","Username harvesting"],"medium",{"iso_27001":["A.8.5"],"cis_v8":["N/A"]},["IA-2","IA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ia-8","NIST 800-53","Identification and Authentication","IA","IA-8","Identification and Authentication (Non-Organizational Users)","Uniquely identify and authenticate non-organizational users.",["Require registration for external users","Implement MFA for external access","Verify identity before provisioning","Review external accounts quarterly"],["External user registration","MFA enrollment","Identity verification","Review records"],["Unauthorized external access"],"high",{"iso_27001":["A.5.16"],"cis_v8":["N/A"]},["IA-2","AC-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-3","NIST 800-53","Incident Response","IR","IR-3","Incident Response Testing","Test the incident response capability to determine effectiveness.",["Conduct annual tabletop exercises","Perform functional exercises","Include all IR team members","Document results and improvements"],["Exercise plans","Results documentation","Improvement actions","Participation records"],["Untested procedures","Unknown gaps"],"high",{"iso_27001":["A.5.24"],"cis_v8":["17.7"]},["IR-2","IR-4","IR-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-5","NIST 800-53","Incident Response","IR","IR-5","Incident Monitoring","Track and document incidents on an ongoing basis.",["Maintain incident tracking system","Record all incident details","Track resolution status","Generate metrics"],["Incident tracking system","Incident records","Status reports","Metrics dashboards"],["Lost incident data","No trending analysis"],"high",{"iso_27001":["A.5.25"],"cis_v8":["17.4"]},["IR-4","IR-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pe-2","NIST 800-53","Physical and Environmental Protection","PE","PE-2","Physical Access Authorizations","Develop and maintain a list of individuals with authorized access to facilities.",["Maintain access list","Review quarterly","Remove terminated personnel immediately","Require sponsor for visitors"],["Access authorization list","Review records","Removal records","Visitor procedures"],["Unauthorized physical access"],"high",{"iso_27001":["A.7.1"],"cis_v8":["N/A"]},["PE-3","PE-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pe-13","NIST 800-53","Physical and Environmental Protection","PE","PE-13","Fire Protection","Employ fire detection and suppression systems.",["Install fire detection systems","Deploy suppression (FM-200, sprinklers)","Test annually","Maintain clear evacuation routes"],["Fire system inspection records","Test results","Suppression system documentation"],["Fire damage","Data loss","Safety hazard"],"high",{"iso_27001":["A.7.5"],"cis_v8":["N/A"]},["PE-14","PE-15"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pe-14","NIST 800-53","Physical and Environmental Protection","PE","PE-14","Environmental Controls","Maintain temperature and humidity levels within acceptable ranges.",["Monitor data center temperature","Set humidity controls","Alert on threshold violations","Maintain HVAC systems"],["Environmental monitoring","HVAC maintenance","Alert records","Temperature logs"],["Equipment failure","Data loss from overheating"],"medium",{"iso_27001":["A.7.12"],"cis_v8":["N/A"]},["PE-13","PE-15"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ps-5","NIST 800-53","Personnel Security","PS","PS-5","Personnel Transfer","Review and confirm ongoing operational need for access when personnel transfer.",["Review access on role change","Remove unnecessary access","Provision new access per new role","Update access within 24 hours"],["Transfer checklists","Access modification records","Review documentation"],["Excessive access after transfer","Privilege accumulation"],"high",{"iso_27001":["A.6.5"],"cis_v8":["N/A"]},["PS-4","AC-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ps-6","NIST 800-53","Personnel Security","PS","PS-6","Access Agreements","Require individuals to sign access agreements before being granted access.",["Define access agreement content","Include acceptable use terms","Require signature before access","Renew annually"],["Signed access agreements","Agreement templates","Renewal records"],["Unclear user obligations","Legal liability"],"medium",{"iso_27001":["A.6.2"],"cis_v8":["N/A"]},["PS-3","PL-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sa-3","NIST 800-53","System and Services Acquisition","SA","SA-3","System Development Life Cycle","Manage the system using a system development life cycle that incorporates security.",["Integrate security into SDLC phases","Conduct security reviews at gates","Require threat modeling","Include security testing"],["SDLC documentation","Gate review records","Threat models","Security test results"],["Insecure systems","Missing security requirements"],"high",{"iso_27001":["A.8.25"],"cis_v8":["16.1"]},["SA-4","SA-11"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sa-11","NIST 800-53","System and Services Acquisition","SA","SA-11","Developer Testing and Evaluation","Require developers to create and implement a security assessment plan.",["Require SAST in CI/CD","Conduct DAST before release","Perform code reviews","Test security controls"],["SAST/DAST results","Code review records","Security test plans","Vulnerability findings"],["Insecure code in production"],"high",{"iso_27001":["A.8.25","A.8.28"],"cis_v8":["16.2","16.12"]},["SA-3","SA-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-4","NIST 800-53","System and Communications Protection","SC","SC-4","Information in Shared System Resources","Prevent unauthorized transfer of information via shared system resources.",["Clear memory after process termination","Implement object reuse controls","Isolate tenant data in shared systems","Sanitize temporary storage"],["Object reuse configuration","Memory management","Isolation controls"],["Information leakage between processes/tenants"],"medium",{"iso_27001":["A.8.22"],"cis_v8":["N/A"]},["SC-7","AC-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-23","NIST 800-53","System and Communications Protection","SC","SC-23","Session Authenticity","Protect the authenticity of communications sessions.",["Implement anti-CSRF tokens","Use secure session IDs","Bind sessions to client attributes","Implement session fixation protection"],["Session management configuration","CSRF protection","Session binding"],["Session hijacking","CSRF attacks"],"high",{"iso_27001":["A.8.5"],"cis_v8":["N/A"]},["SC-8","AC-12"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-si-12","NIST 800-53","System and Information Integrity","SI","SI-12","Information Management and Retention","Manage and retain information within the system in accordance with applicable laws.",["Define retention schedules","Implement automated retention","Dispose of data per schedule","Document retention decisions"],["Retention policy","Automated retention configuration","Disposal records","Legal hold procedures"],["Regulatory non-compliance","Excessive data retention"],"medium",{"iso_27001":["A.5.12","A.8.10"],"cis_v8":["3.1"]},["MP-6","SI-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
]

# ===================== MORE SOC 2 (15) =====================
SOC7=[
ctrl("soc2-cc1-2","SOC 2","Common Criteria","CC1","CC1.2","Board of Directors Oversight","The board of directors demonstrates independence from management and exercises oversight.",["Establish audit committee","Define board oversight responsibilities","Regular security reporting to board","Independent board members"],["Board meeting minutes","Audit committee charter","Security reports to board"],["Lack of governance oversight"],"high",{"nist_800_53":["PM-1"],"iso_27001":["A.5.1"]},["CC1.1","CC1.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc1-5","SOC 2","Common Criteria","CC1","CC1.5","Accountability","The entity holds individuals accountable for their internal control responsibilities.",["Define accountability in job descriptions","Include security in performance reviews","Enforce consequences for violations","Recognize good security behavior"],["Job descriptions","Performance reviews","Disciplinary records","Recognition programs"],["No accountability","Repeated violations"],"medium",{"nist_800_53":["PS-8"],"iso_27001":["A.6.4"]},["CC1.1","CC1.4"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc2-1","SOC 2","Common Criteria","CC2","CC2.1","Information and Communication: Internal","The entity internally communicates information necessary to support the functioning of internal control.",["Communicate security policies","Provide regular security updates","Establish reporting channels","Share incident lessons learned"],["Communication records","Policy distribution","Security newsletters","Reporting procedures"],["Uninformed employees","Communication gaps"],"medium",{"nist_800_53":["AT-2","PL-4"],"iso_27001":["A.5.1"]},["CC2.2","CC2.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc3-1","SOC 2","Common Criteria","CC3","CC3.1","Risk Assessment: Specifies Objectives","The entity specifies objectives with sufficient clarity to enable identification of risks.",["Define security objectives","Align with business goals","Make objectives measurable","Review annually"],["Security objectives documentation","Business alignment","Metrics definitions"],["Unclear security direction","Misaligned priorities"],"medium",{"nist_800_53":["PM-9"],"iso_27001":["A.5.1"]},["CC3.2","CC3.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc3-4","SOC 2","Common Criteria","CC3","CC3.4","Risk Assessment: Considers Fraud","The entity considers the potential for fraud in assessing risks.",["Include fraud scenarios in risk assessment","Assess management override risks","Consider incentives and pressures","Evaluate segregation of duties"],["Fraud risk assessment","Override controls","SoD matrix"],["Fraud","Management override","Financial loss"],"high",{"nist_800_53":["AC-5"],"iso_27001":["A.5.3"]},["CC3.2","CC5.1"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc4-1","SOC 2","Common Criteria","CC4","CC4.1","Monitoring Activities: Ongoing and Separate Evaluations","The entity selects, develops, and performs ongoing and/or separate evaluations.",["Implement continuous monitoring","Conduct periodic assessments","Use automated tools","Report findings to management"],["Monitoring dashboards","Assessment reports","Tool configuration","Management reports"],["Undetected control failures","Degraded security"],"high",{"nist_800_53":["CA-7"],"iso_27001":["A.5.35"]},["CC4.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc5-2","SOC 2","Common Criteria","CC5","CC5.2","Technology General Controls","The entity selects and develops general control activities over technology.",["Implement IT general controls","Control access to technology","Manage technology acquisition","Monitor technology operations"],["ITGC documentation","Access controls","Acquisition procedures","Operations monitoring"],["Technology failures","Unauthorized access"],"high",{"nist_800_53":["CM-2","CM-6"],"iso_27001":["A.8.9"]},["CC5.1","CC5.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-4","SOC 2","Common Criteria","CC6","CC6.4","Physical Access Controls","The entity restricts physical access to facilities and protected information assets.",["Implement badge access","Deploy security cameras","Maintain visitor logs","Restrict server room access"],["Badge system configuration","Camera footage","Visitor logs","Access records"],["Physical theft","Unauthorized access","Sabotage"],"high",{"nist_800_53":["PE-3"],"iso_27001":["A.7.1","A.7.2"]},["CC6.1","CC6.5"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-5","SOC 2","Common Criteria","CC6","CC6.5","Disposal of Assets","The entity disposes of protected information assets in a secure manner.",["Define disposal procedures","Sanitize media before disposal","Obtain destruction certificates","Track disposal activities"],["Disposal procedures","Sanitization records","Destruction certificates","Tracking logs"],["Data leakage from disposed assets"],"medium",{"nist_800_53":["MP-6"],"iso_27001":["A.7.10","A.7.14"]},["CC6.1"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-7","SOC 2","Common Criteria","CC6","CC6.7","Encryption of Data","The entity restricts the transmission, movement, and removal of information to authorized users through encryption.",["Encrypt data in transit (TLS 1.2+)","Encrypt data at rest","Manage encryption keys","Monitor for unencrypted transmissions"],["Encryption configuration","Key management","Monitoring records"],["Data interception","Unauthorized access to stored data"],"high",{"nist_800_53":["SC-8","SC-28"],"iso_27001":["A.8.24"]},["CC6.1","CC6.6"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc7-5","SOC 2","Common Criteria","CC7","CC7.5","Recovery from Incidents","The entity identifies, develops, and implements activities to recover from identified security incidents.",["Implement recovery procedures","Restore from backups","Validate system integrity","Conduct post-recovery testing"],["Recovery procedures","Restoration records","Integrity checks","Post-recovery tests"],["Extended downtime","Incomplete recovery"],"high",{"nist_800_53":["CP-10","IR-4"],"iso_27001":["A.5.26"]},["CC7.3","CC7.4"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-a1-1","SOC 2","Availability","A1","A1.1","Availability Commitments","The entity maintains, monitors, and evaluates current processing capacity and use.",["Define availability SLAs","Monitor uptime","Plan capacity","Alert on degradation"],["SLA documentation","Uptime reports","Capacity plans","Alert configuration"],["Service unavailability","SLA breach"],"high",{"nist_800_53":["CP-2","SC-5"],"iso_27001":["A.8.6","A.8.14"]},["A1.2","A1.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-a1-3","SOC 2","Availability","A1","A1.3","Recovery Testing","The entity tests recovery plan procedures supporting system recovery.",["Test DR annually","Include all critical systems","Document results","Update plans based on findings"],["DR test plans","Test results","Findings","Plan updates"],["Untested recovery","Unknown gaps"],"high",{"nist_800_53":["CP-4"],"iso_27001":["A.5.29"]},["A1.1","A1.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-c1-1","SOC 2","Confidentiality","C1","C1.1","Confidential Information Identification","The entity identifies and maintains confidential information.",["Define confidentiality criteria","Classify information","Label confidential data","Restrict access"],["Classification policy","Labeled data","Access restrictions"],["Confidential data exposure"],"high",{"nist_800_53":["RA-2"],"iso_27001":["A.5.12"]},["C1.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-p1-1","SOC 2","Privacy","P1","P1.1","Privacy Notice","The entity provides notice about its privacy practices.",["Publish privacy notice","Include all required elements","Make easily accessible","Update on changes"],["Privacy notice","Publication records","Update history"],["Privacy violations","Regulatory fines"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["P1.2"],["https://www.aicpa.org/soc2"]),
]

# ===================== MORE PCI DSS (15) =====================
PCI7=[
ctrl("pci-1-2","PCI DSS 4.0","Network Security Controls","REQ-1","1.2","Network Security Controls Configured and Maintained","NSCs are configured and maintained to restrict inbound and outbound traffic.",["Restrict inbound to necessary only","Deny all by default","Review rules semi-annually","Document business justification for each rule"],["Firewall rules","Rule review records","Business justifications","Default deny evidence"],["Unauthorized access","Data exfiltration"],"high",{"nist_800_53":["SC-7"],"iso_27001":["A.8.20"],"cis_v8":["4.4"]},["1.1","1.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-1-4","PCI DSS 4.0","Network Security Controls","REQ-1","1.4","Network Connections Between Trusted and Untrusted Networks are Controlled","NSCs are installed between all trusted and untrusted networks.",["Implement DMZ","Control all internet-facing connections","Restrict CDE access","Monitor boundary traffic"],["DMZ architecture","Boundary controls","CDE segmentation","Monitoring records"],["Direct CDE exposure","Unauthorized access"],"high",{"nist_800_53":["SC-7"],"iso_27001":["A.8.22"],"cis_v8":["13.4"]},["1.1","1.2"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-3-1","PCI DSS 4.0","Protect Stored Account Data","REQ-3","3.1","Processes for Protection of Stored Account Data are Defined","Processes and mechanisms for protecting stored account data are defined and understood.",["Define data retention policy","Minimize stored data","Implement secure deletion","Document storage locations"],["Retention policy","Data flow diagrams","Deletion procedures","Storage inventory"],["Excessive data storage","Compliance violation"],"high",{"nist_800_53":["MP-6","SI-12"],"iso_27001":["A.5.12"],"cis_v8":["3.1"]},["3.2","3.4"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-5-1","PCI DSS 4.0","Protect from Malicious Software","REQ-5","5.1","Processes for Protection from Malicious Software are Defined","Processes and mechanisms for protecting systems from malicious software are defined and understood.",["Define anti-malware strategy","Cover all system types","Include detection and prevention","Address emerging threats"],["Anti-malware policy","Coverage documentation","Strategy reviews"],["Malware infection","Ransomware"],"high",{"nist_800_53":["SI-3"],"iso_27001":["A.8.7"],"cis_v8":["10.1"]},["5.2","5.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-6-2","PCI DSS 4.0","Develop Secure Systems","REQ-6","6.2","Bespoke and Custom Software is Developed Securely","Bespoke and custom software is developed securely following industry standards.",["Train developers on secure coding","Conduct code reviews","Perform SAST/DAST","Address OWASP Top 10"],["Training records","Code review records","SAST/DAST results","OWASP coverage"],["Application vulnerabilities","Data breach via application"],"high",{"nist_800_53":["SA-11","SI-10"],"iso_27001":["A.8.25","A.8.28"],"cis_v8":["16.1","16.12"]},["6.1","6.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-8-2","PCI DSS 4.0","Identify Users and Authenticate Access","REQ-8","8.2","User Identification and Related Accounts are Managed","User identification and related accounts for users and administrators are strictly managed.",["Assign unique IDs","Disable inactive accounts (90 days)","Manage shared accounts with justification","Remove terminated users immediately"],["User ID inventory","Inactive account reports","Shared account justifications","Termination records"],["Shared account abuse","Orphaned accounts"],"high",{"nist_800_53":["AC-2","IA-4"],"iso_27001":["A.5.16"],"cis_v8":["5.1"]},["8.1","8.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-9-1","PCI DSS 4.0","Restrict Physical Access","REQ-9","9.1","Processes for Restricting Physical Access are Defined","Processes and mechanisms for restricting physical access to cardholder data are defined.",["Define physical security zones","Implement access controls","Monitor sensitive areas","Restrict media access"],["Physical security policy","Zone definitions","Access controls","Monitoring records"],["Physical theft","Unauthorized access to CDE"],"high",{"nist_800_53":["PE-3"],"iso_27001":["A.7.1"],"cis_v8":["N/A"]},["9.2","9.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-10-2","PCI DSS 4.0","Log and Monitor","REQ-10","10.2","Audit Logs are Implemented to Support Detection of Anomalies","Audit logs are implemented to support the detection of anomalies and suspicious activity.",["Log all access to CDE","Include admin actions","Record authentication events","Log security events"],["Log configuration","Event coverage","Sample logs"],["Undetected breaches","Insufficient forensics"],"high",{"nist_800_53":["AU-2","AU-12"],"iso_27001":["A.8.15"],"cis_v8":["8.2","8.5"]},["10.1","10.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-10-4","PCI DSS 4.0","Log and Monitor","REQ-10","10.4","Audit Logs are Reviewed to Identify Anomalies","Audit logs are reviewed to identify anomalies or suspicious activity.",["Review logs daily","Implement automated alerting","Investigate anomalies","Document review activities"],["Review procedures","Alert configuration","Investigation records","Review logs"],["Missed security events","Delayed detection"],"high",{"nist_800_53":["AU-6"],"iso_27001":["A.8.15","A.8.16"],"cis_v8":["8.11"]},["10.1","10.2"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-11-4","PCI DSS 4.0","Test Security","REQ-11","11.4","External and Internal Penetration Testing is Performed","External and internal penetration testing is regularly performed and exploitable vulnerabilities are corrected.",["Annual external pentest","Annual internal pentest","Pentest after significant changes","Remediate and retest findings"],["Pentest reports","Remediation records","Retest results","Scope documents"],["Unknown exploitable vulnerabilities"],"high",{"nist_800_53":["CA-8"],"iso_27001":["A.5.35"],"cis_v8":["18.1","18.2"]},["11.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-12-3","PCI DSS 4.0","Information Security Policy","REQ-12","12.3","Cryptographic Cipher Suites and Protocols are Documented","Cryptographic cipher suites and protocols in use are documented and reviewed.",["Document all cryptographic usage","Review annually","Remove weak algorithms","Plan for crypto agility"],["Cryptographic inventory","Review records","Algorithm standards","Migration plans"],["Weak encryption","Compliance gaps"],"medium",{"nist_800_53":["SC-13"],"iso_27001":["A.8.24"],"cis_v8":["3.11"]},["12.1"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-12-6","PCI DSS 4.0","Information Security Policy","REQ-12","12.6","Security Awareness Education is an Ongoing Activity","Security awareness education is an ongoing activity for all personnel.",["Annual security training","Include PCI-specific content","Conduct phishing simulations","Track completion"],["Training program","Completion records","Phishing results","Content materials"],["Human error","Phishing","Policy violations"],"high",{"nist_800_53":["AT-2"],"iso_27001":["A.6.3"],"cis_v8":["14.1"]},["12.1"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-12-8","PCI DSS 4.0","Information Security Policy","REQ-12","12.8","Risk to Information Assets from Third-Party Service Providers is Managed","Risk to information assets associated with TPSP relationships is managed.",["Maintain TPSP inventory","Conduct due diligence","Monitor compliance","Include PCI requirements in agreements"],["TPSP inventory","Due diligence records","Compliance monitoring","Agreements"],["Third-party breach","Compliance gaps"],"high",{"nist_800_53":["SA-9"],"iso_27001":["A.5.19"],"cis_v8":["15.1"]},["12.1"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-12-10","PCI DSS 4.0","Information Security Policy","REQ-12","12.10","Suspected and Confirmed Security Incidents are Responded to Immediately","Suspected and confirmed security incidents that could impact the CDE are responded to immediately.",["Implement IR plan for CDE","Define response procedures","Include notification requirements","Test plan annually"],["IR plan","Response procedures","Notification records","Test results"],["Delayed breach response","Regulatory penalties"],"high",{"nist_800_53":["IR-1","IR-4"],"iso_27001":["A.5.24"],"cis_v8":["17.1"]},["12.1"],["https://www.pcisecuritystandards.org"]),
]

# ===================== MORE CIS (15) =====================
CIS7=[
ctrl("cis-2-5","CIS Controls v8","Inventory and Control of Software Assets","CIS-2","2.5","Allowlist Authorized Software","Use technical controls to ensure only authorized software can execute.",["Implement application whitelisting","Use AppLocker/WDAC on Windows","Block unauthorized executables","Monitor for bypass attempts"],["Whitelisting configuration","Policy rules","Block logs","Bypass alerts"],["Malware execution","Unauthorized tools"],"high",{"nist_800_53":["CM-7","CM-11"],"iso_27001":["A.8.9"]},["2.1","2.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-3-5","CIS Controls v8","Data Protection","CIS-3","3.5","Securely Dispose of Data","Securely dispose of data as outlined in the data management process.",["Define disposal methods per data type","Use secure deletion tools","Obtain destruction certificates","Verify disposal completeness"],["Disposal procedures","Destruction certificates","Verification records"],["Data recovery from disposed media"],"medium",{"nist_800_53":["MP-6"],"iso_27001":["A.8.10"]},["3.1"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-3-7","CIS Controls v8","Data Protection","CIS-3","3.7","Establish and Maintain a Data Classification Scheme","Establish and maintain an overall data classification scheme.",["Define classification levels","Document handling requirements per level","Train employees","Label data appropriately"],["Classification scheme","Handling procedures","Training records","Labeling standards"],["Inappropriate data handling","Over/under protection"],"high",{"nist_800_53":["RA-2"],"iso_27001":["A.5.12"]},["3.1","3.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-4-3","CIS Controls v8","Secure Configuration","CIS-4","4.3","Configure Automatic Session Locking on Enterprise Assets","Configure automatic session locking after a defined period of inactivity.",["Set 15-minute inactivity timeout","Require authentication to unlock","Apply via GPO/MDM","Include all device types"],["Timeout configuration","GPO/MDM settings","Compliance reports"],["Unauthorized access to unattended devices"],"medium",{"nist_800_53":["AC-11"],"iso_27001":["A.8.1"]},["4.1"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-4-8","CIS Controls v8","Secure Configuration","CIS-4","4.8","Uninstall or Disable Unnecessary Services on Enterprise Assets","Uninstall or disable unnecessary services on enterprise assets and software.",["Identify unnecessary services","Disable or remove","Document exceptions","Verify quarterly"],["Service inventory","Disabled services list","Exception documentation","Verification scans"],["Expanded attack surface","Unnecessary vulnerabilities"],"high",{"nist_800_53":["CM-7"],"iso_27001":["A.8.9"]},["4.1","4.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-5-3","CIS Controls v8","Account Management","CIS-5","5.3","Disable Dormant Accounts","Delete or disable any dormant accounts after 45 days of inactivity.",["Identify inactive accounts (45 days)","Disable automatically","Notify account owners","Review monthly"],["Inactive account reports","Disable records","Notification logs"],["Orphaned accounts","Unauthorized access"],"high",{"nist_800_53":["AC-2"],"iso_27001":["A.5.16"]},["5.1","5.2"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-6-4","CIS Controls v8","Access Control Management","CIS-6","6.4","Require MFA for Remote Network Access","Require MFA for all remote network access.",["Implement MFA on VPN","Require for all remote access methods","Support multiple MFA factors","Monitor for MFA bypass"],["MFA configuration","VPN settings","Factor enrollment","Bypass alerts"],["Credential theft enabling remote access"],"high",{"nist_800_53":["IA-2"],"iso_27001":["A.8.5"]},["6.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-7-2","CIS Controls v8","Continuous Vulnerability Management","CIS-7","7.2","Establish and Maintain a Remediation Process","Establish and maintain a risk-based remediation strategy with monthly review.",["Define remediation SLAs by severity","Track remediation progress","Escalate overdue items","Report metrics monthly"],["SLA definitions","Tracking dashboard","Escalation records","Monthly reports"],["Unpatched vulnerabilities","SLA violations"],"high",{"nist_800_53":["SI-2"],"iso_27001":["A.8.8"]},["7.1","7.5"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-7-6","CIS Controls v8","Continuous Vulnerability Management","CIS-7","7.6","Perform Automated Vulnerability Scans of Externally-Exposed Assets","Perform automated vulnerability scans of externally-exposed assets monthly.",["Scan external assets monthly minimum","Use authenticated scans where possible","Prioritize by CVSS","Track remediation"],["External scan reports","Scan schedules","Remediation tracking"],["External exploitation","Compliance gaps"],"high",{"nist_800_53":["RA-5"],"iso_27001":["A.8.8"]},["7.1","7.5"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-8-11","CIS Controls v8","Audit Log Management","CIS-8","8.11","Conduct Audit Log Reviews","Conduct reviews of audit logs to detect anomalies or abnormal events.",["Review critical system logs daily","Implement automated correlation","Investigate anomalies","Document findings"],["Review procedures","Correlation rules","Investigation records","Finding documentation"],["Undetected attacks","Delayed response"],"high",{"nist_800_53":["AU-6"],"iso_27001":["A.8.16"]},["8.2","8.9"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-10-3","CIS Controls v8","Malware Defenses","CIS-10","10.3","Disable Autorun and Autoplay for Removable Media","Disable autorun and autoplay auto-execute functionality for removable media.",["Disable autorun via GPO","Block autoplay","Alert on removable media insertion","Consider blocking USB entirely for sensitive systems"],["GPO configuration","Autorun disabled evidence","USB policy"],["Malware via USB","Autorun exploitation"],"medium",{"nist_800_53":["CM-7"],"iso_27001":["A.8.9"]},["10.1","10.2"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-13-3","CIS Controls v8","Network Monitoring and Defense","CIS-13","13.3","Deploy a Network Intrusion Detection Solution","Deploy a network intrusion detection solution on enterprise assets.",["Deploy IDS at network boundaries","Configure signature and anomaly detection","Tune to reduce false positives","Monitor alerts 24/7"],["IDS deployment","Rule configuration","Tuning records","Alert monitoring"],["Undetected network attacks","Lateral movement"],"high",{"nist_800_53":["SI-4"],"iso_27001":["A.8.16"]},["13.1","13.6"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-13-6","CIS Controls v8","Network Monitoring and Defense","CIS-13","13.6","Collect Network Traffic Flow Logs","Collect network traffic flow logs and/or network traffic to review and alert upon.",["Implement NetFlow/sFlow collection","Store flow data for analysis","Correlate with SIEM","Alert on anomalous flows"],["Flow collection configuration","Storage retention","SIEM integration","Alert rules"],["Undetected data exfiltration","Missed lateral movement"],"high",{"nist_800_53":["AU-12","SI-4"],"iso_27001":["A.8.16"]},["13.1","13.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-14-3","CIS Controls v8","Security Awareness and Skills Training","CIS-14","14.3","Train Workforce on Authentication Best Practices","Train workforce members on authentication best practices.",["Train on password hygiene","Educate on MFA importance","Warn about credential phishing","Promote password managers"],["Training materials","Completion records","Assessment results"],["Weak passwords","MFA resistance","Credential theft"],"high",{"nist_800_53":["AT-2"],"iso_27001":["A.6.3"]},["14.1","14.2"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-17-7","CIS Controls v8","Incident Response Management","CIS-17","17.7","Conduct Routine Incident Response Exercises","Conduct routine incident response exercises and scenarios.",["Conduct tabletop exercises quarterly","Include technical exercises annually","Involve all IR team members","Document lessons learned"],["Exercise plans","Participation records","Results documentation","Improvement actions"],["Untested procedures","Unprepared team"],"high",{"nist_800_53":["IR-3"],"iso_27001":["A.5.24"]},["17.1","17.4"],["https://www.cisecurity.org/controls/v8"]),
]

if __name__=="__main__":
    print("GRC Batch 7...")
    data={"id":"nist-800-53-batch3","name":"NIST 800-53 Rev 5 (Batch 3)","description":"More NIST controls","controls":N7}
    with open(OUTPUT_DIR/"nist_800_53_batch3.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  NIST: {len(N7)}")
    data={"id":"soc2-batch2","name":"SOC 2 (Batch 2)","description":"More SOC 2 criteria","controls":SOC7}
    with open(OUTPUT_DIR/"soc2_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  SOC 2: {len(SOC7)}")
    data={"id":"pci-dss-batch2","name":"PCI DSS 4.0 (Batch 2)","description":"More PCI DSS requirements","controls":PCI7}
    with open(OUTPUT_DIR/"pci_dss_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  PCI DSS: {len(PCI7)}")
    data={"id":"cis-v8-batch3","name":"CIS Controls v8 (Batch 3)","description":"More CIS controls","controls":CIS7}
    with open(OUTPUT_DIR/"cis_v8_batch3.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  CIS: {len(CIS7)}")
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
