#!/usr/bin/env python3
"""GRC Batch 8 — push past 300. GDPR expansion + HIPAA expansion + NIST extras."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== GDPR EXPANSION (12) =====================
GDPR8=[
ctrl("gdpr-art-15","GDPR","Data Subject Rights","CH3","Art.15","Right of Access","Data subjects have the right to obtain confirmation and access to their personal data.",["Implement subject access request (SAR) process","Respond within 30 days","Provide data in portable format","Verify requester identity before disclosure"],["SAR procedures","Response templates","Identity verification process","Response time tracking"],["Non-compliance fines","Data subject complaints"],"high",{"nist_800_53":["IP-2"],"iso_27001":["A.5.12"]},["gdpr-art-17","gdpr-art-20"],["https://gdpr-info.eu/art-15-gdpr/"]),
ctrl("gdpr-art-17","GDPR","Data Subject Rights","CH3","Art.17","Right to Erasure","Data subjects can request deletion of personal data when no longer necessary.",["Define erasure criteria","Implement deletion workflows","Notify third parties of erasure","Document erasure decisions and exceptions"],["Erasure request log","Deletion confirmation","Third-party notifications","Exception documentation"],["Regulatory fines","Reputation damage"],"high",{"nist_800_53":["SI-12"],"iso_27001":["A.5.12"]},["gdpr-art-15","gdpr-art-18"],["https://gdpr-info.eu/art-17-gdpr/"]),
ctrl("gdpr-art-20","GDPR","Data Subject Rights","CH3","Art.20","Right to Data Portability","Data subjects can receive their data in a structured, machine-readable format.",["Provide data in JSON/CSV format","Enable direct transfer to another controller","Implement automated export","Cover only data provided by subject"],["Export functionality","Format documentation","Transfer mechanisms","Scope documentation"],["Non-compliance","Operational burden"],"medium",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["gdpr-art-15"],["https://gdpr-info.eu/art-20-gdpr/"]),
ctrl("gdpr-art-25","GDPR","Data Protection by Design","CH4","Art.25","Data Protection by Design and Default","Implement appropriate technical and organizational measures at design time.",["Conduct privacy impact assessments","Minimize data collection by default","Implement pseudonymization","Apply least privilege to data access"],["DPIA records","Design documentation","Default settings evidence","Pseudonymization implementation"],["Privacy violations","Excessive data collection"],"high",{"nist_800_53":["SA-8"],"iso_27001":["A.5.12","A.8.11"]},["gdpr-art-35"],["https://gdpr-info.eu/art-25-gdpr/"]),
ctrl("gdpr-art-28","GDPR","Processor Obligations","CH4","Art.28","Processor","Processing by a processor shall be governed by a contract with specific requirements.",["Execute Data Processing Agreements (DPA)","Include required clauses","Verify processor compliance","Audit processor annually"],["DPA contracts","Required clause checklist","Compliance verification","Audit reports"],["Unauthorized processing","Liability exposure"],"high",{"nist_800_53":["SA-9"],"iso_27001":["A.5.19","A.5.20"]},["gdpr-art-32"],["https://gdpr-info.eu/art-28-gdpr/"]),
ctrl("gdpr-art-30","GDPR","Records of Processing","CH4","Art.30","Records of Processing Activities","Maintain records of processing activities under controller responsibility.",["Document all processing activities","Include purposes and categories","Record data transfers","Update records on changes"],["Records of processing (ROPA)","Processing inventory","Transfer documentation","Update log"],["Regulatory non-compliance","Inability to demonstrate compliance"],"high",{"nist_800_53":["PM-5"],"iso_27001":["A.5.12"]},["gdpr-art-28"],["https://gdpr-info.eu/art-30-gdpr/"]),
ctrl("gdpr-art-33","GDPR","Breach Notification","CH4","Art.33","Notification to Supervisory Authority","Notify supervisory authority within 72 hours of becoming aware of a personal data breach.",["Implement breach detection mechanisms","Define 72-hour notification process","Prepare notification templates","Assign breach response team"],["Breach detection tools","Notification procedures","Templates","Team assignments"],["Regulatory fines (up to 4% revenue)","Delayed notification penalties"],"high",{"nist_800_53":["IR-6"],"iso_27001":["A.5.24","A.5.26"]},["gdpr-art-34"],["https://gdpr-info.eu/art-33-gdpr/"]),
ctrl("gdpr-art-34","GDPR","Breach Notification","CH4","Art.34","Communication to Data Subject","Communicate personal data breach to data subjects when high risk to rights and freedoms.",["Define high-risk criteria","Prepare subject notification templates","Implement mass notification capability","Document notification decisions"],["Risk assessment criteria","Notification templates","Communication records","Decision documentation"],["Reputation damage","Data subject harm"],"high",{"nist_800_53":["IR-6"],"iso_27001":["A.5.26"]},["gdpr-art-33"],["https://gdpr-info.eu/art-34-gdpr/"]),
ctrl("gdpr-art-35","GDPR","Impact Assessment","CH4","Art.35","Data Protection Impact Assessment","Carry out DPIA where processing is likely to result in high risk.",["Identify high-risk processing","Conduct systematic DPIA","Consult DPO","Implement mitigations before processing"],["DPIA methodology","Completed DPIAs","DPO consultation records","Mitigation plans"],["Unmitigated privacy risks","Regulatory action"],"high",{"nist_800_53":["RA-3"],"iso_27001":["A.5.12"]},["gdpr-art-25","gdpr-art-36"],["https://gdpr-info.eu/art-35-gdpr/"]),
ctrl("gdpr-art-37","GDPR","Data Protection Officer","CH4","Art.37","Designation of DPO","Designate a Data Protection Officer where required by regulation.",["Assess DPO requirement","Appoint qualified DPO","Ensure independence","Provide adequate resources"],["DPO appointment letter","Qualification evidence","Independence documentation","Resource allocation"],["Non-compliance","Lack of oversight"],"high",{"nist_800_53":["PM-2"],"iso_27001":["A.5.1"]},["gdpr-art-38","gdpr-art-39"],["https://gdpr-info.eu/art-37-gdpr/"]),
ctrl("gdpr-art-44","GDPR","International Transfers","CH5","Art.44","General Principle for Transfers","Transfer of personal data to third countries only with adequate safeguards.",["Assess adequacy decisions","Implement Standard Contractual Clauses (SCCs)","Conduct Transfer Impact Assessments","Document transfer mechanisms"],["Adequacy assessment","SCCs","TIA documentation","Transfer records"],["Illegal data transfers","Regulatory fines"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["gdpr-art-46"],["https://gdpr-info.eu/art-44-gdpr/"]),
ctrl("gdpr-art-46","GDPR","International Transfers","CH5","Art.46","Transfers Subject to Appropriate Safeguards","Transfers may take place where appropriate safeguards are provided.",["Use Standard Contractual Clauses","Implement Binding Corporate Rules","Obtain certification under approved mechanism","Supplement with additional measures if needed"],["SCCs signed","BCR documentation","Certification evidence","Supplementary measures"],["Invalid transfer basis","Regulatory enforcement"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["gdpr-art-44"],["https://gdpr-info.eu/art-46-gdpr/"]),
]

# ===================== HIPAA EXPANSION (12) =====================
HIPAA8=[
ctrl("hipaa-164-308-a1","HIPAA","Administrative Safeguards","164.308","164.308(a)(1)","Security Management Process","Implement policies and procedures to prevent, detect, contain, and correct security violations.",["Conduct risk analysis","Implement risk management program","Apply sanctions for violations","Review information system activity"],["Risk analysis report","Risk management plan","Sanction policy","Activity review logs"],["Security violations","PHI breach"],"high",{"nist_800_53":["PL-1","RA-3"],"iso_27001":["A.5.1"]},["hipaa-164-308-a8"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-308-a3","HIPAA","Administrative Safeguards","164.308","164.308(a)(3)","Workforce Security","Implement policies to ensure workforce members have appropriate access to ePHI.",["Implement authorization procedures","Establish workforce clearance","Define termination procedures","Restrict access based on role"],["Authorization records","Clearance documentation","Termination checklists","Role-based access matrix"],["Unauthorized ePHI access","Insider threat"],"high",{"nist_800_53":["AC-2","PS-3"],"iso_27001":["A.5.15","A.6.1"]},["hipaa-164-308-a4"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-308-a4","HIPAA","Administrative Safeguards","164.308","164.308(a)(4)","Information Access Management","Implement policies for authorizing access to ePHI consistent with applicable requirements.",["Implement access authorization","Establish access modification procedures","Isolate healthcare clearinghouse functions","Review access rights periodically"],["Access authorization policy","Modification records","Isolation documentation","Access reviews"],["Unauthorized access to ePHI","Compliance violation"],"high",{"nist_800_53":["AC-1","AC-2"],"iso_27001":["A.5.15"]},["hipaa-164-308-a3"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-308-a5","HIPAA","Administrative Safeguards","164.308","164.308(a)(5)","Security Awareness and Training","Implement a security awareness and training program for all workforce members.",["Provide security reminders","Implement malicious software protection training","Train on login monitoring","Train on password management"],["Training materials","Completion records","Reminder communications","Assessment results"],["Human error","Phishing","Weak passwords"],"high",{"nist_800_53":["AT-2","AT-3"],"iso_27001":["A.6.3"]},["hipaa-164-308-a1"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-308-a6","HIPAA","Administrative Safeguards","164.308","164.308(a)(6)","Security Incident Procedures","Implement policies to address security incidents.",["Define incident response procedures","Identify and respond to incidents","Mitigate harmful effects","Document incidents and outcomes"],["IR procedures","Incident reports","Mitigation records","Outcome documentation"],["Uncontained incidents","PHI breach"],"high",{"nist_800_53":["IR-1","IR-4"],"iso_27001":["A.5.24"]},["hipaa-164-308-a1"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-308-a7","HIPAA","Administrative Safeguards","164.308","164.308(a)(7)","Contingency Plan","Establish policies for responding to an emergency or occurrence that damages ePHI systems.",["Create data backup plan","Develop disaster recovery plan","Create emergency mode operations plan","Test and revise contingency plans"],["Backup plan","DR plan","Emergency procedures","Test results"],["Data loss","Extended downtime","ePHI unavailability"],"high",{"nist_800_53":["CP-1","CP-2","CP-9"],"iso_27001":["A.5.29","A.5.30"]},["hipaa-164-308-a1"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-310-a1","HIPAA","Physical Safeguards","164.310","164.310(a)(1)","Facility Access Controls","Implement policies to limit physical access to ePHI systems and facilities.",["Implement contingency operations access","Create facility security plan","Implement access control and validation","Maintain maintenance records"],["Facility security plan","Access control records","Validation procedures","Maintenance logs"],["Physical theft","Unauthorized facility access"],"high",{"nist_800_53":["PE-1","PE-2","PE-3"],"iso_27001":["A.7.1","A.7.2"]},["hipaa-164-310-b"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-310-b","HIPAA","Physical Safeguards","164.310","164.310(b)","Workstation Use","Implement policies specifying proper functions and physical attributes of workstations.",["Define acceptable workstation use","Specify physical safeguards for workstations","Restrict workstation locations","Implement screen privacy"],["Workstation use policy","Physical safeguard documentation","Location restrictions","Privacy screen deployment"],["Unauthorized viewing of ePHI","Workstation theft"],"medium",{"nist_800_53":["PE-18"],"iso_27001":["A.7.7"]},["hipaa-164-310-a1","hipaa-164-310-c"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-310-d","HIPAA","Physical Safeguards","164.310","164.310(d)","Device and Media Controls","Implement policies governing receipt and removal of hardware and electronic media containing ePHI.",["Implement disposal procedures","Implement media re-use procedures","Maintain accountability records","Create data backup before movement"],["Disposal records","Sanitization records","Accountability tracking","Backup verification"],["ePHI on disposed media","Lost devices"],"high",{"nist_800_53":["MP-6","MP-7"],"iso_27001":["A.7.10","A.7.14"]},["hipaa-164-310-a1"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-312-a","HIPAA","Technical Safeguards","164.312","164.312(a)","Access Control","Implement technical policies to allow access only to authorized persons or software.",["Assign unique user identification","Implement emergency access procedure","Implement automatic logoff","Implement encryption and decryption"],["Unique ID assignment","Emergency access procedures","Logoff configuration","Encryption implementation"],["Unauthorized ePHI access","Unencrypted ePHI exposure"],"high",{"nist_800_53":["AC-2","AC-7","SC-28"],"iso_27001":["A.8.3","A.8.5"]},["hipaa-164-312-d"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-312-b","HIPAA","Technical Safeguards","164.312","164.312(b)","Audit Controls","Implement hardware, software, and procedural mechanisms to record and examine activity.",["Implement audit logging on ePHI systems","Record access to ePHI","Review audit logs regularly","Retain logs per policy"],["Audit log configuration","Access records","Review procedures","Retention settings"],["Undetected unauthorized access","Insufficient forensics"],"high",{"nist_800_53":["AU-2","AU-12"],"iso_27001":["A.8.15"]},["hipaa-164-312-a"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
ctrl("hipaa-164-312-e","HIPAA","Technical Safeguards","164.312","164.312(e)","Transmission Security","Implement technical security measures to guard against unauthorized access to ePHI during transmission.",["Implement integrity controls","Implement encryption for transmission","Use TLS 1.2+ for all ePHI transfers","Monitor for unencrypted transmissions"],["Encryption configuration","TLS certificates","Integrity controls","Monitoring records"],["ePHI interception","Man-in-the-middle attacks"],"high",{"nist_800_53":["SC-8","SC-13"],"iso_27001":["A.8.24"]},["hipaa-164-312-a"],["https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/"]),
]

# ===================== NIST EXTRAS (11) =====================
NIST8=[
ctrl("nist-ma-2","NIST 800-53","Maintenance","MA","MA-2","Controlled Maintenance","Schedule, document, and review records of maintenance and repairs on system components.",["Schedule preventive maintenance","Document all maintenance activities","Review maintenance records","Approve maintenance before execution"],["Maintenance schedule","Work orders","Review records","Approval documentation"],["System degradation","Unplanned outages"],"medium",{"iso_27001":["A.7.13"],"cis_v8":["N/A"]},["MA-3","MA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ma-5","NIST 800-53","Maintenance","MA","MA-5","Maintenance Personnel","Establish a process for maintenance personnel authorization and supervise non-authorized personnel.",["Maintain authorized maintenance personnel list","Escort non-authorized personnel","Verify credentials before access","Log all maintenance activities"],["Authorized personnel list","Escort records","Credential verification","Activity logs"],["Unauthorized system access via maintenance"],"medium",{"iso_27001":["A.7.13"],"cis_v8":["N/A"]},["MA-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-mp-2","NIST 800-53","Media Protection","MP","MP-2","Media Access","Restrict access to digital and non-digital media to authorized individuals.",["Define media access authorizations","Implement physical media controls","Restrict digital media access","Log media access"],["Access authorization list","Physical controls","Digital access controls","Access logs"],["Unauthorized data access via media"],"medium",{"iso_27001":["A.7.10"],"cis_v8":["3.1"]},["MP-4","MP-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-mp-6","NIST 800-53","Media Protection","MP","MP-6","Media Sanitization","Sanitize system media prior to disposal, release, or reuse.",["Define sanitization methods per media type","Use approved sanitization tools","Verify sanitization completeness","Document sanitization activities"],["Sanitization procedures","Tool approvals","Verification records","Sanitization logs"],["Data recovery from disposed media"],"high",{"iso_27001":["A.7.10","A.7.14"],"cis_v8":["3.5"]},["MP-2","MP-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pl-4","NIST 800-53","Planning","PL","PL-4","Rules of Behavior","Establish and provide rules describing responsibilities and expected behavior for system use.",["Define acceptable use rules","Include social media guidance","Address mobile device use","Require signed acknowledgment"],["Rules of behavior document","Signed acknowledgments","Social media policy","Mobile use policy"],["Misuse of systems","Policy violations"],"medium",{"iso_27001":["A.5.10"],"cis_v8":["N/A"]},["PL-2","PS-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pm-9","NIST 800-53","Program Management","PM","PM-9","Risk Management Strategy","Develop a comprehensive strategy to manage risk to organizational operations.",["Define risk tolerance levels","Establish risk assessment methodology","Integrate into decision-making","Review strategy annually"],["Risk management strategy","Risk tolerance documentation","Methodology documentation","Annual review records"],["Inconsistent risk decisions","Unmanaged risks"],"high",{"iso_27001":["A.5.1"],"cis_v8":["N/A"]},["RA-3","PM-28"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pm-14","NIST 800-53","Program Management","PM","PM-14","Testing, Training, and Monitoring","Implement a process for ensuring security testing, training, and monitoring are conducted.",["Integrate testing into SDLC","Conduct regular security training","Implement continuous monitoring","Report results to leadership"],["Testing schedule","Training program","Monitoring configuration","Leadership reports"],["Untested controls","Untrained staff","Unmonitored systems"],"high",{"iso_27001":["A.5.35"],"cis_v8":["N/A"]},["CA-7","AT-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ra-7","NIST 800-53","Risk Assessment","RA","RA-7","Risk Response","Respond to findings from security assessments, monitoring, and audits.",["Define risk response options (accept, mitigate, transfer, avoid)","Document risk decisions","Implement selected responses","Track response effectiveness"],["Risk response decisions","Implementation records","Effectiveness metrics","Risk register updates"],["Unaddressed risks","Ineffective responses"],"high",{"iso_27001":["A.5.1"],"cis_v8":["N/A"]},["RA-3","RA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sa-9","NIST 800-53","System and Services Acquisition","SA","SA-9","External System Services","Require external service providers to comply with organizational security requirements.",["Define security requirements for providers","Include in contracts","Monitor provider compliance","Conduct periodic assessments"],["Provider contracts","Security requirements","Compliance monitoring","Assessment reports"],["Third-party compromise","Supply chain risk"],"high",{"iso_27001":["A.5.19","A.5.21"],"cis_v8":["15.1"]},["SA-4","SR-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sr-3","NIST 800-53","Supply Chain Risk Management","SR","SR-3","Supply Chain Controls and Processes","Establish processes to identify and address supply chain risks.",["Assess supplier security posture","Include security in procurement","Monitor supply chain threats","Diversify critical suppliers"],["Supplier assessments","Procurement requirements","Threat monitoring","Diversification strategy"],["Supply chain compromise","Single point of failure"],"high",{"iso_27001":["A.5.19","A.5.21"],"cis_v8":["15.1"]},["SA-9","SR-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sr-5","NIST 800-53","Supply Chain Risk Management","SR","SR-5","Acquisition Strategies, Tools, and Methods","Employ acquisition strategies, contract tools, and procurement methods to protect against supply chain risks.",["Use trusted suppliers","Require tamper-evident packaging","Implement component authenticity verification","Include security testing requirements"],["Trusted supplier list","Packaging requirements","Authenticity verification","Testing requirements"],["Counterfeit components","Tampered products"],"medium",{"iso_27001":["A.5.19"],"cis_v8":["N/A"]},["SR-3","SA-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
]

if __name__=="__main__":
    print("GRC Batch 8 — pushing past 300...")
    data={"id":"gdpr-batch2","name":"GDPR (Batch 2)","description":"Expanded GDPR articles","controls":GDPR8}
    with open(OUTPUT_DIR/"gdpr_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  GDPR: {len(GDPR8)}")
    data={"id":"hipaa-batch2","name":"HIPAA (Batch 2)","description":"Expanded HIPAA safeguards","controls":HIPAA8}
    with open(OUTPUT_DIR/"hipaa_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  HIPAA: {len(HIPAA8)}")
    data={"id":"nist-800-53-batch4","name":"NIST 800-53 Rev 5 (Batch 4)","description":"Additional NIST controls","controls":NIST8}
    with open(OUTPUT_DIR/"nist_800_53_batch4.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  NIST: {len(NIST8)}")
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
