#!/usr/bin/env python3
"""GRC Batch 3 — CIS Controls v8."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

CIS=[
ctrl("cis-1-1","CIS Controls v8","Inventory and Control of Enterprise Assets","CIS-1","1.1","Establish and Maintain Detailed Enterprise Asset Inventory","Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets.",["Deploy automated discovery tools","Include all asset types (hardware, virtual, cloud)","Update inventory within 24 hours of changes","Assign owners to all assets"],["Asset inventory database","Discovery scan results","Owner assignments","Update procedures"],["Unknown assets","Shadow IT","Unmanaged vulnerabilities"],"high",{"nist_800_53":["CM-8"],"iso_27001":["A.5.9"]},["1.2","1.3","1.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-1-2","CIS Controls v8","Inventory and Control of Enterprise Assets","CIS-1","1.2","Address Unauthorized Assets","Ensure unauthorized assets are either removed, denied network access, or quarantined.",["Implement NAC (802.1X)","Alert on new unknown devices","Quarantine unauthorized assets","Review weekly"],["NAC configuration","Alert records","Quarantine logs","Review records"],["Rogue devices","Unauthorized access","Malware introduction"],"high",{"nist_800_53":["CM-8"],"iso_27001":["A.5.9"]},["1.1","1.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-2-1","CIS Controls v8","Inventory and Control of Software Assets","CIS-2","2.1","Establish and Maintain a Software Inventory","Maintain an inventory of all authorized software installed on enterprise assets.",["Use software inventory tools","Include version information","Track license compliance","Update on changes"],["Software inventory","Version records","License tracking","Update logs"],["Unauthorized software","License violations","Unpatched applications"],"high",{"nist_800_53":["CM-8","CM-7"],"iso_27001":["A.5.9"]},["2.2","2.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-2-3","CIS Controls v8","Inventory and Control of Software Assets","CIS-2","2.3","Address Unauthorized Software","Ensure unauthorized software is removed or the inventory is updated.",["Implement application whitelisting","Block unauthorized installations","Alert on new software","Review monthly"],["Whitelisting configuration","Block logs","Alert records"],["Malware","Unauthorized tools","Compliance violations"],"high",{"nist_800_53":["CM-7","CM-11"],"iso_27001":["A.8.9"]},["2.1","2.2"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-3-3","CIS Controls v8","Data Protection","CIS-3","3.3","Configure Data Access Control Lists","Configure data access control lists based on a user's need to know.",["Implement RBAC","Apply least privilege","Review access quarterly","Document access decisions"],["ACL configuration","Access review records","RBAC documentation"],["Unauthorized data access","Data breach","Privilege creep"],"high",{"nist_800_53":["AC-3","AC-6"],"iso_27001":["A.5.15"]},["3.1","3.2","3.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-3-11","CIS Controls v8","Data Protection","CIS-3","3.11","Encrypt Sensitive Data at Rest","Encrypt sensitive data at rest on servers, applications, and databases.",["Use AES-256 encryption","Encrypt database columns with sensitive data","Implement full-disk encryption","Manage keys separately"],["Encryption configuration","Key management procedures","FDE deployment records"],["Data breach from stolen media","Unauthorized access to stored data"],"high",{"nist_800_53":["SC-28"],"iso_27001":["A.8.24"]},["3.10","3.12"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-4-1","CIS Controls v8","Secure Configuration of Enterprise Assets and Software","CIS-4","4.1","Establish and Maintain a Secure Configuration Process","Establish and maintain a secure configuration process for enterprise assets and software.",["Define security baselines using CIS Benchmarks","Implement configuration management tools","Scan for compliance monthly","Document approved deviations"],["Baseline documentation","CIS Benchmark scan results","Compliance reports","Deviation records"],["Misconfigurations","Default credentials","Expanded attack surface"],"high",{"nist_800_53":["CM-2","CM-6"],"iso_27001":["A.8.9"]},["4.2","4.3","4.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-5-1","CIS Controls v8","Account Management","CIS-5","5.1","Establish and Maintain an Account Inventory","Maintain an inventory of all accounts including user, admin, and service accounts.",["Inventory all account types","Include service accounts","Track privileged accounts separately","Review quarterly"],["Account inventory","Privileged account list","Service account register","Review records"],["Orphaned accounts","Unknown privileged access","Unauthorized accounts"],"high",{"nist_800_53":["AC-2"],"iso_27001":["A.5.16"]},["5.2","5.3","5.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-5-4","CIS Controls v8","Account Management","CIS-5","5.4","Restrict Administrator Privileges to Dedicated Administrator Accounts","Restrict administrator privileges to dedicated administrator accounts on enterprise assets.",["Separate admin and user accounts","No daily work with admin accounts","Implement PAM for admin access","Log all admin activity"],["Admin account inventory","PAM configuration","Admin activity logs","Separation policy"],["Lateral movement","Credential theft","Privilege abuse"],"high",{"nist_800_53":["AC-6"],"iso_27001":["A.5.15","A.8.2"]},["5.1","5.2","5.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-6-3","CIS Controls v8","Access Control Management","CIS-6","6.3","Require MFA for Externally-Exposed Applications","Require MFA for all externally-exposed enterprise applications.",["Implement MFA on VPN, email, cloud apps","Support hardware tokens and authenticator apps","Enforce for all external access","Monitor MFA bypass attempts"],["MFA configuration","Enrollment records","Bypass attempt logs"],["Credential theft","Phishing","Account compromise"],"high",{"nist_800_53":["IA-2"],"iso_27001":["A.8.5"]},["6.1","6.2","6.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-7-1","CIS Controls v8","Continuous Vulnerability Management","CIS-7","7.1","Establish and Maintain a Vulnerability Management Process","Establish and maintain a documented vulnerability management process.",["Define scanning frequency","Establish remediation SLAs","Track metrics","Report to management"],["VM policy","SLA definitions","Metrics dashboards","Management reports"],["Unpatched vulnerabilities","Exploitation","Compliance gaps"],"high",{"nist_800_53":["RA-5","SI-2"],"iso_27001":["A.8.8"]},["7.2","7.3","7.5"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-8-2","CIS Controls v8","Audit Log Management","CIS-8","8.2","Collect Audit Logs","Collect audit logs from enterprise assets including endpoints, network devices, and servers.",["Configure logging on all assets","Forward to central SIEM","Include authentication, access, and change events","Ensure timestamp accuracy"],["SIEM configuration","Log source inventory","Collection verification","NTP configuration"],["Undetected incidents","Insufficient forensics","Compliance gaps"],"high",{"nist_800_53":["AU-2","AU-12"],"iso_27001":["A.8.15"]},["8.1","8.3","8.5"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-10-1","CIS Controls v8","Malware Defenses","CIS-10","10.1","Deploy and Maintain Anti-Malware Software","Deploy and maintain anti-malware software on all enterprise assets.",["Deploy EDR on all endpoints and servers","Enable real-time protection","Configure automatic updates","Monitor detection events"],["EDR deployment records","Coverage reports","Update status","Detection logs"],["Malware infection","Ransomware","Data theft"],"high",{"nist_800_53":["SI-3"],"iso_27001":["A.8.7"]},["10.2","10.3","10.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-11-1","CIS Controls v8","Data Recovery","CIS-11","11.1","Establish and Maintain a Data Recovery Process","Establish and maintain a data recovery process including scope, frequency, and testing.",["Define backup scope and frequency","Implement 3-2-1 strategy","Test restoration quarterly","Document RTO/RPO"],["Backup policy","Test results","RTO/RPO documentation","Recovery procedures"],["Data loss","Extended downtime","Business disruption"],"high",{"nist_800_53":["CP-9"],"iso_27001":["A.8.13"]},["11.2","11.3","11.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-13-1","CIS Controls v8","Network Monitoring and Defense","CIS-13","13.1","Centralize Security Event Alerting","Centralize security event alerting across enterprise assets.",["Deploy SIEM","Define correlation rules","Establish alert priorities","Implement 24/7 monitoring or on-call"],["SIEM architecture","Correlation rules","Alert procedures","On-call schedule"],["Undetected attacks","Delayed response","Alert fatigue"],"high",{"nist_800_53":["SI-4","AU-6"],"iso_27001":["A.8.15","A.8.16"]},["13.2","13.3","13.6"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-14-1","CIS Controls v8","Security Awareness and Skills Training","CIS-14","14.1","Establish and Maintain a Security Awareness Program","Establish and maintain a security awareness program to influence behavior.",["Annual training for all employees","Monthly phishing simulations","Role-based training","Track effectiveness metrics"],["Training program documentation","Completion records","Phishing results","Effectiveness metrics"],["Human error","Phishing susceptibility","Policy violations"],"high",{"nist_800_53":["AT-2"],"iso_27001":["A.6.3"]},["14.2","14.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-15-1","CIS Controls v8","Service Provider Management","CIS-15","15.1","Establish and Maintain an Inventory of Service Providers","Maintain an inventory of service providers including classification and contact information.",["Inventory all service providers","Classify by data access level","Assign relationship owners","Review annually"],["Provider inventory","Classification records","Owner assignments","Review records"],["Unknown third-party risk","Unmanaged vendors","Supply chain gaps"],"high",{"nist_800_53":["SA-9"],"iso_27001":["A.5.19"]},["15.2","15.3","15.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-17-1","CIS Controls v8","Incident Response Management","CIS-17","17.1","Designate Personnel to Manage Incident Handling","Designate one or more personnel to manage the incident handling process.",["Assign IR team lead","Define team roles","Establish on-call rotation","Provide training and tools"],["IR team roster","Role definitions","On-call schedule","Training records"],["No incident ownership","Delayed response","Confusion during incidents"],"high",{"nist_800_53":["IR-1","IR-2"],"iso_27001":["A.5.24"]},["17.2","17.3","17.4"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-18-1","CIS Controls v8","Penetration Testing","CIS-18","18.1","Establish and Maintain a Penetration Testing Program","Establish and maintain a penetration testing program appropriate to the size and complexity of the enterprise.",["Conduct annual penetration tests","Define scope and rules of engagement","Remediate findings within SLA","Retest after remediation"],["Pentest reports","Scope documents","Remediation tracking","Retest results"],["Unknown exploitable vulnerabilities","False sense of security"],"high",{"nist_800_53":["CA-8"],"iso_27001":["A.5.35","A.8.8"]},["18.2","18.3"],["https://www.cisecurity.org/controls/v8"]),
]

if __name__=="__main__":
    print("GRC Batch 3 — CIS Controls v8...")
    data = {"id":"cis-v8","name":"CIS Controls v8","description":"Center for Internet Security Critical Security Controls Version 8","controls":CIS}
    path = OUTPUT_DIR / "cis_v8.json"
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  CIS v8: {len(CIS)} controls")
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
