#!/usr/bin/env python3
"""GRC Bulk Generator — adds controls across multiple frameworks."""
import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"
RISK_DIR = Path(__file__).parent.parent / "data" / "risks"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RISK_DIR.mkdir(parents=True, exist_ok=True)

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== NIST 800-53 EXPANDED (30 more) =====================
NIST_NEW = [
ctrl("nist-ac-4","NIST 800-53","Access Control","AC","AC-4","Information Flow Enforcement","Enforce approved authorizations for controlling the flow of information within the system and between systems.",["Implement network segmentation","Deploy firewalls between zones","Use DLP for data flow control","Classify data by sensitivity level"],["Firewall rule sets","Network diagrams","DLP policy configuration","Data flow documentation"],["Unauthorized data transfer","Data leakage","Cross-zone contamination"],"high",{"iso_27001":["A.8.22"],"cis_v8":["13.1","13.4"],"soc2":["CC6.6"]},["AC-3","SC-7"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-5","NIST 800-53","Access Control","AC","AC-5","Separation of Duties","Enforce separation of duties through assigned access authorizations to prevent fraud and errors.",["Identify conflicting duties","Implement role-based separation","Require dual authorization for critical actions","Document separation matrix"],["Separation of duties matrix","Role definitions","Dual-control procedures","Access review records"],["Fraud","Unauthorized changes","Single point of failure"],"high",{"iso_27001":["A.5.3"],"cis_v8":["6.8"],"soc2":["CC6.1"]},["AC-2","AC-3","AC-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-7","NIST 800-53","Access Control","AC","AC-7","Unsuccessful Logon Attempts","Enforce a limit on consecutive invalid logon attempts and take action when limit exceeded.",["Set lockout threshold (5 attempts)","Define lockout duration (15 min)","Alert security on repeated failures","Log all failed attempts"],["Lockout policy configuration","Failed logon event logs","Alert rules","Account lockout reports"],["Brute-force attacks","Credential stuffing","Unauthorized access"],"high",{"iso_27001":["A.8.5"],"cis_v8":["5.2"],"soc2":["CC6.1"],"pci_dss":["8.1.6"]},["AC-2","IA-2","SI-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-11","NIST 800-53","Access Control","AC","AC-11","Device Lock","Prevent access to the system by initiating a device lock after inactivity period.",["Set screen lock timeout (15 min max)","Require authentication to unlock","Apply via GPO/MDM","Include mobile devices"],["GPO/MDM configuration","Screen lock policy","Compliance scan results"],["Unauthorized physical access","Unattended workstation abuse"],"medium",{"iso_27001":["A.8.1"],"cis_v8":["4.3"],"soc2":["CC6.1"]},["AC-2","AC-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-at-2","NIST 800-53","Awareness and Training","AT","AT-2","Literacy Training and Awareness","Provide security awareness training to all users including recognizing social engineering.",["Annual security awareness training","Monthly phishing simulations","Role-based training for IT staff","New hire security orientation"],["Training completion records","Phishing simulation results","Training materials","Attendance logs"],["Phishing susceptibility","Social engineering","Human error"],"high",{"iso_27001":["A.6.3"],"cis_v8":["14.1","14.2","14.3"],"soc2":["CC1.4"]},["AT-1","AT-3","PM-13"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-3","NIST 800-53","Audit and Accountability","AU","AU-3","Content of Audit Records","Ensure audit records contain sufficient information to establish what occurred.",["Include timestamp, source, user, action, outcome","Log source/destination IPs","Record before/after values for changes","Include session identifiers"],["Log format documentation","Sample log entries","SIEM parsing rules","Log completeness validation"],["Insufficient forensic evidence","Inability to reconstruct events"],"high",{"iso_27001":["A.8.15"],"cis_v8":["8.5"],"soc2":["CC7.2"],"pci_dss":["10.3"]},["AU-2","AU-6","AU-12"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-6","NIST 800-53","Audit and Accountability","AU","AU-6","Audit Record Review, Analysis, and Reporting","Review and analyze audit records for indications of inappropriate or unusual activity.",["Implement SIEM with correlation rules","Define review frequency (daily for critical)","Establish alert thresholds","Create dashboards for security events"],["SIEM configuration","Alert rules","Review schedules","Incident tickets from log review"],["Undetected breaches","Delayed incident response","Compliance gaps"],"high",{"iso_27001":["A.8.15","A.8.16"],"cis_v8":["8.11"],"soc2":["CC7.2","CC7.3"],"pci_dss":["10.6"]},["AU-2","AU-3","SI-4","IR-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-9","NIST 800-53","Audit and Accountability","AU","AU-9","Protection of Audit Information","Protect audit information and tools from unauthorized access, modification, and deletion.",["Restrict log access to security team","Implement write-once storage","Forward logs to central SIEM immediately","Encrypt logs in transit and at rest"],["Log access controls","SIEM architecture","Log integrity verification","Backup procedures"],["Log tampering","Evidence destruction","Cover-up of attacks"],"high",{"iso_27001":["A.8.15"],"cis_v8":["8.9"],"soc2":["CC7.2"]},["AU-3","AU-6","SC-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ca-2","NIST 800-53","Assessment, Authorization, and Monitoring","CA","CA-2","Control Assessments","Assess security controls periodically to determine effectiveness.",["Conduct annual security assessments","Use automated scanning tools","Perform penetration testing","Document findings and remediation"],["Assessment reports","Scan results","Penetration test reports","Remediation tracking"],["Unknown vulnerabilities","Ineffective controls","Compliance gaps"],"high",{"iso_27001":["A.5.35","A.5.36"],"cis_v8":["18.1","18.2"],"soc2":["CC4.1"]},["RA-5","CA-7","PM-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-3","NIST 800-53","Configuration Management","CM","CM-3","Configuration Change Control","Manage and control changes to the system using a formal change management process.",["Implement change advisory board (CAB)","Require testing before production","Document all changes","Implement rollback procedures"],["Change requests","CAB meeting minutes","Test results","Change logs"],["Unauthorized changes","System instability","Security regression"],"high",{"iso_27001":["A.8.32"],"cis_v8":["4.1"],"soc2":["CC8.1"],"pci_dss":["6.4"]},["CM-2","CM-5","CM-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-6","NIST 800-53","Configuration Management","CM","CM-6","Configuration Settings","Establish and enforce security configuration settings for IT products.",["Apply CIS benchmarks","Use configuration management tools","Scan for compliance regularly","Document approved deviations"],["CIS benchmark scan results","Configuration standards","Deviation approvals","Compliance dashboards"],["Misconfigurations","Default credentials","Unnecessary services"],"high",{"iso_27001":["A.8.9"],"cis_v8":["4.1","4.2"],"soc2":["CC7.1"],"pci_dss":["2.2"]},["CM-2","CM-3","CM-7"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-7","NIST 800-53","Configuration Management","CM","CM-7","Least Functionality","Configure systems to provide only essential capabilities and disable unnecessary functions.",["Disable unused services and ports","Remove unnecessary software","Implement application whitelisting","Harden OS configurations"],["Hardening checklists","Port scan results","Software inventory","Whitelisting configuration"],["Expanded attack surface","Unnecessary vulnerabilities","Resource waste"],"high",{"iso_27001":["A.8.9"],"cis_v8":["4.8","2.3"],"soc2":["CC7.1"]},["CM-2","CM-6","SC-7"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-8","NIST 800-53","Configuration Management","CM","CM-8","System Component Inventory","Maintain an accurate, current inventory of all system components.",["Implement automated discovery tools","Update inventory on changes","Include hardware, software, and firmware","Assign owners to all assets"],["Asset inventory database","Discovery scan results","Owner assignments","Inventory review records"],["Unknown assets","Shadow IT","Unmanaged vulnerabilities"],"high",{"iso_27001":["A.5.9"],"cis_v8":["1.1","1.2","2.1"],"soc2":["CC6.1"]},["CM-2","PM-5","RA-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cp-9","NIST 800-53","Contingency Planning","CP","CP-9","System Backup","Conduct backups of system data, software, and configurations at defined frequency.",["Implement 3-2-1 backup strategy","Test restoration monthly","Encrypt backup data","Store offsite copies"],["Backup schedules","Restoration test results","Backup encryption configuration","Offsite storage records"],["Data loss","Ransomware impact","Business disruption"],"high",{"iso_27001":["A.8.13"],"cis_v8":["11.1","11.2","11.3"],"soc2":["CC7.5","A1.2"],"pci_dss":["9.5"]},["CP-2","CP-10","MP-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ia-5","NIST 800-53","Identification and Authentication","IA","IA-5","Authenticator Management","Manage system authenticators (passwords, tokens, certificates) throughout their lifecycle.",["Enforce password complexity (14+ chars)","Implement password expiration policies","Protect authenticator storage (hashing)","Revoke compromised authenticators immediately"],["Password policy configuration","Hash algorithm documentation","Authenticator lifecycle procedures","Compromise response records"],["Weak credentials","Credential theft","Unauthorized access"],"high",{"iso_27001":["A.5.17","A.8.5"],"cis_v8":["5.2","5.3"],"soc2":["CC6.1"],"pci_dss":["8.2","8.5"]},["IA-2","AC-7","SC-13"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-4","NIST 800-53","Incident Response","IR","IR-4","Incident Handling","Implement incident handling capability including preparation, detection, analysis, containment, eradication, and recovery.",["Define incident severity levels","Establish containment procedures","Create communication templates","Conduct post-incident reviews"],["IR procedures","Incident tickets","Post-mortem reports","Communication logs"],["Delayed response","Uncontained breaches","Repeated incidents"],"high",{"iso_27001":["A.5.25","A.5.26"],"cis_v8":["17.4","17.5","17.6"],"soc2":["CC7.3","CC7.4"]},["IR-1","IR-5","IR-6","IR-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-6","NIST 800-53","Incident Response","IR","IR-6","Incident Reporting","Report incidents to appropriate authorities and organizational officials.",["Define reporting timelines by severity","Establish reporting channels","Include regulatory notification requirements","Document lessons learned"],["Reporting procedures","Notification records","Regulatory filings","Lessons learned documents"],["Regulatory non-compliance","Delayed stakeholder notification","Repeated incidents"],"high",{"iso_27001":["A.5.24","A.6.8"],"cis_v8":["17.2"],"soc2":["CC7.3"]},["IR-1","IR-4","IR-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-mp-6","NIST 800-53","Media Protection","MP","MP-6","Media Sanitization","Sanitize system media prior to disposal, release, or reuse.",["Define sanitization methods by media type","Use NIST 800-88 guidelines","Verify sanitization effectiveness","Maintain sanitization records"],["Sanitization procedures","Destruction certificates","Verification records","Media tracking logs"],["Data leakage from disposed media","Unauthorized data recovery"],"medium",{"iso_27001":["A.7.10","A.7.14"],"cis_v8":["3.5"],"soc2":["CC6.5"],"pci_dss":["9.8"]},["MP-2","MP-4","SC-28"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pe-3","NIST 800-53","Physical and Environmental Protection","PE","PE-3","Physical Access Control","Enforce physical access authorizations at entry/exit points to facilities.",["Implement badge access systems","Maintain visitor logs","Deploy security cameras","Escort visitors in sensitive areas"],["Access control system configuration","Visitor logs","Camera footage retention","Badge assignment records"],["Unauthorized physical access","Theft","Sabotage"],"high",{"iso_27001":["A.7.1","A.7.2"],"cis_v8":["N/A"],"soc2":["CC6.4"],"pci_dss":["9.1","9.2"]},["PE-2","PE-6","PE-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pl-2","NIST 800-53","Planning","PL","PL-2","System Security and Privacy Plans","Develop security plans that describe controls and implementation details.",["Document system boundaries","Describe implemented controls","Define roles and responsibilities","Review and update annually"],["System security plan (SSP)","Control implementation descriptions","Plan review records","Authorization documentation"],["Undocumented security posture","Unclear responsibilities","Audit failures"],"high",{"iso_27001":["A.5.1"],"cis_v8":["N/A"],"soc2":["CC1.1"]},["PL-1","CA-2","PM-1"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ps-3","NIST 800-53","Personnel Security","PS","PS-3","Personnel Screening","Screen individuals prior to authorizing access to systems.",["Conduct background checks","Verify employment history","Check criminal records for sensitive roles","Re-screen periodically for high-risk positions"],["Background check records","Screening policy","Re-screening schedule","Clearance documentation"],["Insider threat","Unvetted access to sensitive data"],"high",{"iso_27001":["A.6.1"],"cis_v8":["N/A"],"soc2":["CC1.4"]},["PS-2","PS-4","PS-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ra-5","NIST 800-53","Risk Assessment","RA","RA-5","Vulnerability Monitoring and Scanning","Monitor and scan for vulnerabilities and remediate in accordance with risk assessment.",["Scan weekly (internal) and monthly (external)","Define remediation SLAs by severity","Track remediation progress","Validate fixes with re-scanning"],["Scan reports","Remediation tracking","SLA compliance metrics","Re-scan validation"],["Unpatched vulnerabilities","Exploitation of known flaws"],"high",{"iso_27001":["A.8.8"],"cis_v8":["7.1","7.2","7.5","7.6"],"soc2":["CC7.1"],"pci_dss":["6.1","11.2"]},["RA-3","SI-2","CM-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sa-9","NIST 800-53","System and Services Acquisition","SA","SA-9","External System Services","Require external service providers to comply with organizational security requirements.",["Include security requirements in contracts","Conduct vendor security assessments","Monitor vendor compliance","Define data handling requirements"],["Vendor contracts with security clauses","Assessment reports","SLA documentation","Data processing agreements"],["Third-party breach","Supply chain compromise","Data exposure"],"high",{"iso_27001":["A.5.19","A.5.20","A.5.21"],"cis_v8":["15.1","15.2"],"soc2":["CC9.2"]},["SA-4","SR-1","PM-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-8","NIST 800-53","System and Communications Protection","SC","SC-8","Transmission Confidentiality and Integrity","Protect the confidentiality and integrity of transmitted information.",["Encrypt all data in transit (TLS 1.2+)","Implement VPN for remote access","Use certificate-based authentication","Disable unencrypted protocols"],["TLS configuration","VPN architecture","Certificate management","Protocol scan results"],["Data interception","Man-in-the-middle attacks","Eavesdropping"],"high",{"iso_27001":["A.8.24"],"cis_v8":["3.10"],"soc2":["CC6.6","CC6.7"],"pci_dss":["4.1"]},["SC-7","SC-13","AC-17"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-13","NIST 800-53","System and Communications Protection","SC","SC-13","Cryptographic Protection","Implement cryptographic mechanisms to prevent unauthorized disclosure and modification.",["Use FIPS-validated cryptographic modules","Implement AES-256 for data at rest","Use RSA-2048+ or ECC for key exchange","Manage cryptographic keys securely"],["Cryptographic standards documentation","Key management procedures","FIPS validation certificates","Encryption configuration"],["Data exposure","Weak encryption","Key compromise"],"high",{"iso_27001":["A.8.24"],"cis_v8":["3.11"],"soc2":["CC6.1"],"pci_dss":["3.4","4.1"]},["SC-8","SC-12","SC-28"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-28","NIST 800-53","System and Communications Protection","SC","SC-28","Protection of Information at Rest","Protect the confidentiality and integrity of information at rest.",["Encrypt databases and file systems","Use full-disk encryption on endpoints","Implement database-level encryption","Manage encryption keys separately from data"],["Encryption configuration","Key management procedures","FDE deployment records","Database encryption settings"],["Data breach from stolen media","Unauthorized data access"],"high",{"iso_27001":["A.8.24"],"cis_v8":["3.11"],"soc2":["CC6.1","CC6.7"],"pci_dss":["3.4"]},["SC-8","SC-13","MP-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-si-3","NIST 800-53","System and Information Integrity","SI","SI-3","Malicious Code Protection","Implement malicious code protection mechanisms at entry and exit points.",["Deploy endpoint protection (EDR/AV)","Enable real-time scanning","Update signatures automatically","Scan removable media on insertion"],["EDR/AV deployment records","Signature update logs","Scan results","Malware incident reports"],["Malware infection","Ransomware","Data theft"],"high",{"iso_27001":["A.8.7"],"cis_v8":["10.1","10.2","10.3"],"soc2":["CC7.1"],"pci_dss":["5.1","5.2"]},["SI-2","SI-4","SC-7"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-si-4","NIST 800-53","System and Information Integrity","SI","SI-4","System Monitoring","Monitor the system to detect attacks, unauthorized connections, and anomalies.",["Deploy SIEM with correlation","Implement network monitoring (IDS/IPS)","Monitor for unauthorized changes","Alert on anomalous behavior"],["SIEM configuration","IDS/IPS rules","Monitoring dashboards","Alert response procedures"],["Undetected attacks","Delayed incident response","Insider threats"],"high",{"iso_27001":["A.8.15","A.8.16"],"cis_v8":["8.2","8.5","8.11","13.3"],"soc2":["CC7.2"],"pci_dss":["10.6","11.4"]},["AU-6","IR-4","SI-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
]

# ===================== SAVE =====================
if __name__ == "__main__":
    print("GRC Bulk Generate...")
    # Save as new framework file
    data = {"id":"nist-800-53-expanded","name":"NIST 800-53 Rev 5 (Expanded)","description":"Security and Privacy Controls — expanded set","controls":NIST_NEW}
    path = OUTPUT_DIR / "nist_800_53_expanded.json"
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  NIST expanded: {len(NIST_NEW)} controls")
    
    # Count total
    total = 0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d = json.load(f)
            if isinstance(d, list): total += len(d)
            elif "controls" in d: total += len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
