#!/usr/bin/env python3
"""GRC Batch 6 — push to 200. More ISO + HIPAA + more policies."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"
POLICY_DIR = Path(__file__).parent.parent / "data" / "policies"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== MORE ISO 27001 (20) =====================
ISO6=[
ctrl("iso-5-2","ISO 27001","Organizational Controls","A.5","A.5.2","Information Security Roles and Responsibilities","Information security roles and responsibilities shall be defined and allocated.",["Define CISO role","Assign security responsibilities to all roles","Document in job descriptions","Review on organizational changes"],["Role definitions","RACI matrix","Job descriptions","Org chart"],["Unclear accountability","Gaps in security coverage"],"high",{"nist_800_53":["PM-2"],"cis_v8":["N/A"]},["A.5.1","A.5.4"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-4","ISO 27001","Organizational Controls","A.5","A.5.4","Management Responsibilities","Management shall require all personnel to apply information security in accordance with the established policies.",["Include security in performance reviews","Provide resources for security","Lead by example","Enforce consequences for violations"],["Management directives","Resource allocation","Performance criteria","Enforcement records"],["Lack of management support","Security culture gaps"],"high",{"nist_800_53":["PM-1"],"cis_v8":["N/A"]},["A.5.1","A.5.2"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-14","ISO 27001","Organizational Controls","A.5","A.5.14","Information Transfer","Rules, procedures, or agreements for information transfer shall be in place.",["Define transfer procedures","Encrypt data in transit","Use secure file transfer","Log all transfers"],["Transfer policy","Encryption standards","Secure transfer tools","Transfer logs"],["Data interception","Unauthorized disclosure"],"high",{"nist_800_53":["SC-8"],"cis_v8":["3.10"]},["A.5.12","A.8.24"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-25","ISO 27001","Organizational Controls","A.5","A.5.25","Assessment and Decision on Information Security Events","Information security events shall be assessed and decided if they are to be classified as incidents.",["Define event classification criteria","Implement triage process","Document decisions","Escalate confirmed incidents"],["Classification criteria","Triage procedures","Decision records","Escalation logs"],["Missed incidents","Delayed response"],"high",{"nist_800_53":["IR-4","IR-5"],"cis_v8":["17.4"]},["A.5.24","A.5.26"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-26","ISO 27001","Organizational Controls","A.5","A.5.26","Response to Information Security Incidents","Information security incidents shall be responded to in accordance with documented procedures.",["Follow IR procedures","Contain and eradicate","Preserve evidence","Communicate to stakeholders"],["IR procedures","Containment actions","Evidence preservation","Communication records"],["Uncontained breaches","Evidence loss"],"high",{"nist_800_53":["IR-4","IR-6"],"cis_v8":["17.4","17.5"]},["A.5.24","A.5.25","A.5.27"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-27","ISO 27001","Organizational Controls","A.5","A.5.27","Learning from Information Security Incidents","Knowledge gained from incidents shall be used to strengthen controls.",["Conduct post-incident reviews","Document lessons learned","Update procedures","Share knowledge across teams"],["Post-mortem reports","Lessons learned","Procedure updates","Knowledge sharing records"],["Repeated incidents","Failure to improve"],"high",{"nist_800_53":["IR-4"],"cis_v8":["17.8"]},["A.5.24","A.5.26"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-30","ISO 27001","Organizational Controls","A.5","A.5.30","ICT Readiness for Business Continuity","ICT readiness shall be planned, implemented, maintained, and tested based on business continuity objectives.",["Define ICT recovery objectives","Implement redundancy","Test failover procedures","Maintain DR site"],["RTO/RPO definitions","Redundancy architecture","Test results","DR documentation"],["Extended ICT outages","Business disruption"],"high",{"nist_800_53":["CP-2","CP-9"],"cis_v8":["11.1"]},["A.5.29"],["https://www.iso.org/standard/27001"]),
ctrl("iso-6-2","ISO 27001","People Controls","A.6","A.6.2","Terms and Conditions of Employment","Employment agreements shall state personnel and organization responsibilities for information security.",["Include security clauses in contracts","Define confidentiality obligations","Specify acceptable use","Include post-employment obligations"],["Employment contracts","NDA agreements","Security clauses","Post-employment terms"],["Unclear obligations","Legal exposure"],"medium",{"nist_800_53":["PS-6"],"cis_v8":["N/A"]},["A.6.1","A.6.5"],["https://www.iso.org/standard/27001"]),
ctrl("iso-6-5","ISO 27001","People Controls","A.6","A.6.5","Responsibilities After Termination or Change of Employment","Information security responsibilities that remain valid after termination shall be defined and enforced.",["Define post-employment obligations","Enforce NDAs","Revoke all access immediately","Conduct exit procedures"],["NDA enforcement","Access revocation records","Exit checklists","Post-employment obligations"],["Data theft on departure","Continued access"],"high",{"nist_800_53":["PS-4","PS-5"],"cis_v8":["N/A"]},["A.6.1","A.6.2"],["https://www.iso.org/standard/27001"]),
ctrl("iso-7-4","ISO 27001","Physical Controls","A.7","A.7.4","Physical Security Monitoring","Premises shall be continuously monitored for unauthorized physical access.",["Deploy CCTV systems","Monitor 24/7","Retain footage per policy","Alert on unauthorized access"],["CCTV system","Monitoring procedures","Retention records","Alert logs"],["Undetected physical intrusion","Theft"],"high",{"nist_800_53":["PE-6"],"cis_v8":["N/A"]},["A.7.1","A.7.2"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-3","ISO 27001","Technological Controls","A.8","A.8.3","Information Access Restriction","Access to information shall be restricted in accordance with the access control policy.",["Implement application-level access controls","Restrict database access","Control API access","Log access attempts"],["Application ACLs","Database permissions","API authentication","Access logs"],["Unauthorized data access","Data breach"],"high",{"nist_800_53":["AC-3"],"cis_v8":["3.3"]},["A.5.15","A.8.5"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-10","ISO 27001","Technological Controls","A.8","A.8.10","Information Deletion","Information stored in systems and devices shall be deleted when no longer required.",["Implement automated deletion","Define retention periods","Verify deletion completeness","Document deletion activities"],["Retention schedules","Deletion logs","Verification records","Automated deletion configuration"],["Data exposure","Compliance violations","Storage waste"],"medium",{"nist_800_53":["MP-6"],"cis_v8":["3.5"]},["A.5.12","A.8.13"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-12","ISO 27001","Technological Controls","A.8","A.8.12","Data Leakage Prevention","Data leakage prevention measures shall be applied to systems and networks containing sensitive information.",["Deploy DLP solutions","Monitor data transfers","Block unauthorized exfiltration","Alert on policy violations"],["DLP configuration","Monitoring rules","Block records","Alert logs"],["Data exfiltration","Insider threat","Compliance violations"],"high",{"nist_800_53":["AC-4","SC-7"],"cis_v8":["3.13"]},["A.5.12","A.8.20"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-16","ISO 27001","Technological Controls","A.8","A.8.16","Monitoring Activities","Networks, systems, and applications shall be monitored for anomalous behavior.",["Implement SIEM","Define anomaly baselines","Alert on deviations","Review alerts daily"],["SIEM configuration","Baseline documentation","Alert rules","Review records"],["Undetected attacks","Delayed response"],"high",{"nist_800_53":["SI-4"],"cis_v8":["8.11","13.1"]},["A.8.15","A.8.17"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-22","ISO 27001","Technological Controls","A.8","A.8.22","Segregation of Networks","Groups of information services, users, and systems shall be segregated in networks.",["Implement VLANs","Deploy firewalls between segments","Restrict inter-segment traffic","Monitor cross-segment flows"],["Network segmentation design","VLAN configuration","Firewall rules","Traffic monitoring"],["Lateral movement","Blast radius expansion"],"high",{"nist_800_53":["SC-7","AC-4"],"cis_v8":["13.4"]},["A.8.20","A.8.21"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-23","ISO 27001","Technological Controls","A.8","A.8.23","Web Filtering","Access to external websites shall be managed to reduce exposure to malicious content.",["Implement web proxy/filter","Block malicious categories","Log web access","Update block lists regularly"],["Web filter configuration","Category blocks","Access logs","Update records"],["Malware delivery","Phishing","Data exfiltration via web"],"medium",{"nist_800_53":["SC-7"],"cis_v8":["9.2"]},["A.8.20","A.8.7"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-26","ISO 27001","Technological Controls","A.8","A.8.26","Application Security Requirements","Information security requirements shall be identified and specified when developing or acquiring applications.",["Define security requirements in specs","Include OWASP Top 10 coverage","Require security testing","Document acceptance criteria"],["Security requirements","OWASP coverage","Test plans","Acceptance criteria"],["Insecure applications","Missing security features"],"high",{"nist_800_53":["SA-4"],"cis_v8":["16.1"]},["A.8.25","A.8.28"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-32","ISO 27001","Technological Controls","A.8","A.8.32","Change Management","Changes to information processing facilities and systems shall be subject to change management procedures.",["Implement formal change process","Require testing and approval","Document all changes","Maintain rollback capability"],["Change management policy","Change records","Test results","Rollback procedures"],["Unauthorized changes","System instability","Security regression"],"high",{"nist_800_53":["CM-3"],"cis_v8":["4.1"]},["A.8.9","A.8.25"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-34","ISO 27001","Technological Controls","A.8","A.8.34","Protection of Information Systems During Audit Testing","Audit tests and activities involving assessment of operational systems shall be planned and agreed.",["Schedule audits to minimize disruption","Use read-only tools where possible","Restrict audit access","Protect audit data"],["Audit schedules","Tool approvals","Access restrictions","Data protection measures"],["System disruption during audits","Audit data exposure"],"medium",{"nist_800_53":["CA-2"],"cis_v8":["18.1"]},["A.5.35"],["https://www.iso.org/standard/27001"]),
]

# ===================== HIPAA (10) =====================
HIPAA=[
ctrl("hipaa-164-308-a1","HIPAA","Administrative Safeguards","164.308","164.308(a)(1)","Security Management Process","Implement policies and procedures to prevent, detect, contain, and correct security violations.",["Conduct risk analysis","Implement risk management","Apply sanctions for violations","Review activity regularly"],["Risk analysis","Risk management plan","Sanction policy","Activity review records"],["PHI breach","Regulatory fines","Patient harm"],"high",{"nist_800_53":["RA-3","PM-9"],"iso_27001":["A.5.1"]},["164.308(a)(2)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-308-a3","HIPAA","Administrative Safeguards","164.308","164.308(a)(3)","Workforce Security","Implement policies to ensure workforce members have appropriate access to ePHI.",["Implement authorization procedures","Supervise workforce access","Terminate access on departure","Conduct clearance procedures"],["Authorization procedures","Access records","Termination checklists","Clearance documentation"],["Unauthorized PHI access","Insider threat"],"high",{"nist_800_53":["AC-2","PS-3"],"iso_27001":["A.5.15","A.6.1"]},["164.308(a)(4)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-308-a4","HIPAA","Administrative Safeguards","164.308","164.308(a)(4)","Information Access Management","Implement policies for authorizing access to ePHI consistent with the minimum necessary standard.",["Implement role-based access","Apply minimum necessary","Isolate healthcare clearinghouse functions","Review access periodically"],["RBAC configuration","Minimum necessary policy","Access reviews"],["Excessive PHI access","Minimum necessary violations"],"high",{"nist_800_53":["AC-3","AC-6"],"iso_27001":["A.5.15"]},["164.308(a)(3)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-308-a5","HIPAA","Administrative Safeguards","164.308","164.308(a)(5)","Security Awareness and Training","Implement a security awareness and training program for all workforce members.",["Provide HIPAA training annually","Include phishing awareness","Train on password management","Address malicious software"],["Training records","Completion certificates","Training materials","Phishing results"],["Human error","PHI exposure","Phishing"],"high",{"nist_800_53":["AT-2"],"iso_27001":["A.6.3"]},["164.308(a)(1)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-308-a6","HIPAA","Administrative Safeguards","164.308","164.308(a)(6)","Security Incident Procedures","Implement policies to address security incidents.",["Define incident response procedures","Identify and respond to incidents","Mitigate harmful effects","Document incidents"],["IR procedures","Incident reports","Mitigation records","Documentation"],["Unmanaged incidents","PHI breach","Regulatory penalties"],"high",{"nist_800_53":["IR-1","IR-4"],"iso_27001":["A.5.24"]},["164.308(a)(1)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-312-a1","HIPAA","Technical Safeguards","164.312","164.312(a)(1)","Access Control","Implement technical policies to allow access only to authorized persons or software programs.",["Implement unique user identification","Provide emergency access procedure","Implement automatic logoff","Encrypt ePHI"],["User ID assignment","Emergency access procedures","Logoff configuration","Encryption settings"],["Unauthorized ePHI access","Shared accounts"],"high",{"nist_800_53":["AC-2","AC-3","IA-2"],"iso_27001":["A.5.15","A.8.5"]},["164.312(a)(2)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-312-b","HIPAA","Technical Safeguards","164.312","164.312(b)","Audit Controls","Implement hardware, software, and procedural mechanisms to record and examine access to ePHI.",["Implement audit logging","Record access to ePHI systems","Review logs regularly","Retain logs per policy"],["Audit log configuration","Access records","Review procedures","Retention policy"],["Undetected unauthorized access","Insufficient evidence"],"high",{"nist_800_53":["AU-2","AU-6"],"iso_27001":["A.8.15"]},["164.312(a)(1)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-312-c","HIPAA","Technical Safeguards","164.312","164.312(c)","Integrity","Implement policies to protect ePHI from improper alteration or destruction.",["Implement integrity controls","Use checksums/hashes","Monitor for unauthorized changes","Implement version control"],["Integrity mechanisms","Hash verification","Change monitoring","Version control"],["Data corruption","Unauthorized modification"],"high",{"nist_800_53":["SI-7"],"iso_27001":["A.8.9"]},["164.312(a)(1)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-312-d","HIPAA","Technical Safeguards","164.312","164.312(d)","Person or Entity Authentication","Implement procedures to verify that a person or entity seeking access to ePHI is who they claim to be.",["Implement MFA","Use strong authentication","Verify identity before access","Log authentication events"],["MFA configuration","Authentication procedures","Verification records","Auth logs"],["Identity fraud","Unauthorized access to PHI"],"high",{"nist_800_53":["IA-2","IA-5"],"iso_27001":["A.8.5"]},["164.312(a)(1)"],["https://www.hhs.gov/hipaa"]),
ctrl("hipaa-164-312-e","HIPAA","Technical Safeguards","164.312","164.312(e)","Transmission Security","Implement technical security measures to guard against unauthorized access to ePHI during transmission.",["Encrypt ePHI in transit","Use TLS 1.2+","Implement integrity controls","Monitor transmissions"],["Encryption configuration","TLS settings","Integrity mechanisms","Monitoring records"],["PHI interception","Man-in-the-middle"],"high",{"nist_800_53":["SC-8"],"iso_27001":["A.8.24"]},["164.312(a)(1)"],["https://www.hhs.gov/hipaa"]),
]

if __name__=="__main__":
    print("GRC Batch 6 — ISO + HIPAA...")
    data={"id":"iso-27001-batch2","name":"ISO 27001:2022 (Batch 2)","description":"Additional ISO 27001 Annex A controls","controls":ISO6}
    with open(OUTPUT_DIR/"iso_27001_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  ISO batch 2: {len(ISO6)}")
    data={"id":"hipaa","name":"HIPAA","description":"Health Insurance Portability and Accountability Act — Security Rule","controls":HIPAA}
    with open(OUTPUT_DIR/"hipaa.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  HIPAA: {len(HIPAA)}")
    # Add policies
    POLICY_DIR.mkdir(parents=True, exist_ok=True)
    policies = {
        "password_policy": "# Password Policy\n\n## 1. Purpose\nEstablish requirements for creating and managing passwords.\n\n## 2. Requirements\n- Minimum 14 characters\n- Mix of uppercase, lowercase, numbers, symbols\n- No dictionary words or personal info\n- Change every 90 days (or on compromise)\n- MFA required for all remote access\n- No password reuse (last 12)\n\n## 3. Storage\n- Passwords stored using bcrypt/argon2\n- Never stored in plaintext\n- Password managers encouraged\n\n## 4. Enforcement\nNon-compliance results in account lockout and disciplinary action.",
        "vendor_management": "# Vendor Management Policy\n\n## 1. Purpose\nManage security risks from third-party vendors and service providers.\n\n## 2. Vendor Assessment\n- Security questionnaire for all new vendors\n- Annual reassessment for critical vendors\n- SOC 2 or ISO 27001 certification preferred\n\n## 3. Contracts\n- Include data protection clauses\n- Right-to-audit provisions\n- Breach notification requirements (72 hours)\n- Data return/destruction on termination\n\n## 4. Monitoring\n- Review vendor security posture quarterly\n- Monitor for vendor breaches\n- Maintain vendor risk register",
        "data_classification": "# Data Classification Policy\n\n## 1. Classification Levels\n\n| Level | Description | Examples |\n|-------|-------------|----------|\n| Public | No restrictions | Marketing materials |\n| Internal | Business use only | Internal memos |\n| Confidential | Restricted access | Financial data, PII |\n| Restricted | Highest protection | Trade secrets, PHI |\n\n## 2. Handling Requirements\n- Public: No special handling\n- Internal: Don't share externally\n- Confidential: Encrypt in transit/rest, access control\n- Restricted: Encrypt always, MFA, audit logging, DLP\n\n## 3. Labeling\nAll documents must be labeled with classification level.",
        "change_management": "# Change Management Policy\n\n## 1. Purpose\nEnsure all changes to IT systems are planned, tested, approved, and documented.\n\n## 2. Change Types\n- Standard: Pre-approved, low risk\n- Normal: Requires CAB approval\n- Emergency: Expedited approval, post-review\n\n## 3. Process\n1. Submit change request\n2. Impact assessment\n3. Testing in non-production\n4. CAB review and approval\n5. Implementation with rollback plan\n6. Post-implementation review\n\n## 4. Documentation\nAll changes recorded in change management system with before/after states.",
        "business_continuity": "# Business Continuity Policy\n\n## 1. Purpose\nEnsure critical business functions continue during and after a disruption.\n\n## 2. Key Definitions\n- RTO: Maximum acceptable downtime\n- RPO: Maximum acceptable data loss\n- MTPD: Maximum tolerable period of disruption\n\n## 3. Requirements\n- BIA conducted annually\n- BCP tested semi-annually\n- DR site maintained\n- Communication plan established\n\n## 4. Critical Functions\nIdentified through Business Impact Analysis with assigned RTOs and RPOs.",
    }
    for name, content in policies.items():
        with open(POLICY_DIR/f"{name}.md",'w') as f: f.write(content)
    print(f"  Policies: {len(policies)} new")
    # Total
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
