#!/usr/bin/env python3
"""GRC Batch 4 — SOC 2 + PCI DSS + more risks + policies."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"
RISK_DIR = Path(__file__).parent.parent / "data" / "risks"
POLICY_DIR = Path(__file__).parent.parent / "data" / "policies"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== SOC 2 Trust Service Criteria (20) =====================
SOC2=[
ctrl("soc2-cc1-1","SOC 2","Common Criteria","CC1","CC1.1","COSO Principle 1: Demonstrates Commitment to Integrity and Ethical Values","The entity demonstrates a commitment to integrity and ethical values.",["Establish code of conduct","Communicate ethical expectations","Enforce consequences for violations","Board oversight of ethics"],["Code of conduct","Ethics training records","Violation reports","Board meeting minutes"],["Ethical violations","Fraud","Reputational damage"],"high",{"nist_800_53":["PL-4"],"iso_27001":["A.5.1"]},["CC1.2","CC1.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc1-4","SOC 2","Common Criteria","CC1","CC1.4","COSO Principle 4: Demonstrates Commitment to Competence","The entity demonstrates commitment to attract, develop, and retain competent individuals.",["Define competency requirements","Provide ongoing training","Conduct performance evaluations","Maintain succession plans"],["Job descriptions","Training records","Performance reviews","Succession plans"],["Skill gaps","Key person dependency","Inadequate security knowledge"],"medium",{"nist_800_53":["AT-2","PS-2"],"iso_27001":["A.6.3"]},["CC1.1","CC1.5"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc3-2","SOC 2","Common Criteria","CC3","CC3.2","Risk Assessment: Identifies Risks","The entity identifies risks to the achievement of its objectives.",["Conduct annual risk assessments","Identify internal and external threats","Assess likelihood and impact","Maintain risk register"],["Risk assessment reports","Risk register","Threat analysis","Risk scoring methodology"],["Unknown risks","Unmanaged threats","Inadequate controls"],"high",{"nist_800_53":["RA-3"],"iso_27001":["A.5.7"]},["CC3.1","CC3.3","CC3.4"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc5-1","SOC 2","Common Criteria","CC5","CC5.1","Control Activities: Selects and Develops Control Activities","The entity selects and develops control activities that mitigate risks.",["Map controls to identified risks","Implement preventive and detective controls","Document control procedures","Test control effectiveness"],["Control matrix","Procedure documentation","Test results","Gap analysis"],["Unmitigated risks","Ineffective controls"],"high",{"nist_800_53":["CA-2","PL-2"],"iso_27001":["A.5.1"]},["CC5.2","CC5.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-1","SOC 2","Common Criteria","CC6","CC6.1","Logical and Physical Access Controls","The entity implements logical access security over protected information assets.",["Implement RBAC","Require MFA","Conduct access reviews","Manage privileged access"],["RBAC configuration","MFA enrollment","Access review records","PAM logs"],["Unauthorized access","Data breach","Privilege abuse"],"high",{"nist_800_53":["AC-2","AC-3","IA-2"],"iso_27001":["A.5.15","A.5.16"]},["CC6.2","CC6.3","CC6.6"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-2","SOC 2","Common Criteria","CC6","CC6.2","Registration and Authorization","Prior to issuing system credentials, the entity registers and authorizes new users.",["Formal access request process","Manager approval required","Verify identity before provisioning","Document all access grants"],["Access request forms","Approval records","Identity verification","Provisioning logs"],["Unauthorized account creation","Identity fraud"],"high",{"nist_800_53":["AC-2","IA-4"],"iso_27001":["A.5.16"]},["CC6.1","CC6.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-3","SOC 2","Common Criteria","CC6","CC6.3","Role-Based Access and Least Privilege","The entity authorizes, modifies, or removes access based on roles and least privilege.",["Implement role-based access","Review quarterly","Remove access on role change","Apply least privilege"],["Role definitions","Quarterly review records","Access modification logs"],["Privilege creep","Excessive access","Insider threat"],"high",{"nist_800_53":["AC-6"],"iso_27001":["A.5.15"]},["CC6.1","CC6.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc6-6","SOC 2","Common Criteria","CC6","CC6.6","System Boundaries and Network Security","The entity implements controls to prevent or detect unauthorized access at system boundaries.",["Deploy firewalls","Implement IDS/IPS","Segment networks","Monitor boundary traffic"],["Firewall rules","IDS/IPS configuration","Network diagrams","Monitoring dashboards"],["Network intrusion","Lateral movement","Data exfiltration"],"high",{"nist_800_53":["SC-7"],"iso_27001":["A.8.20"]},["CC6.1","CC7.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc7-1","SOC 2","Common Criteria","CC7","CC7.1","Detection of Changes","The entity uses detection and monitoring procedures to identify changes to configurations and vulnerabilities.",["Implement vulnerability scanning","Monitor configuration changes","Deploy file integrity monitoring","Alert on unauthorized changes"],["Scan reports","FIM alerts","Change detection logs","Configuration baselines"],["Undetected vulnerabilities","Unauthorized changes","Configuration drift"],"high",{"nist_800_53":["SI-2","CM-3"],"iso_27001":["A.8.8","A.8.9"]},["CC7.2","CC7.3"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc7-2","SOC 2","Common Criteria","CC7","CC7.2","Monitoring System Components","The entity monitors system components for anomalies indicative of malicious acts or natural disasters.",["Deploy SIEM","Implement anomaly detection","Monitor 24/7","Define alert thresholds"],["SIEM configuration","Monitoring procedures","Alert records","Incident correlation"],["Undetected attacks","Delayed response"],"high",{"nist_800_53":["SI-4","AU-6"],"iso_27001":["A.8.15","A.8.16"]},["CC7.1","CC7.3","CC7.4"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc7-3","SOC 2","Common Criteria","CC7","CC7.3","Incident Response","The entity evaluates events to determine whether they constitute security incidents.",["Define incident classification criteria","Implement triage procedures","Establish escalation paths","Document all decisions"],["Classification criteria","Triage procedures","Escalation matrix","Incident tickets"],["Missed incidents","Delayed escalation","Inconsistent handling"],"high",{"nist_800_53":["IR-4","IR-5"],"iso_27001":["A.5.25"]},["CC7.2","CC7.4","CC7.5"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc7-4","SOC 2","Common Criteria","CC7","CC7.4","Incident Containment and Remediation","The entity responds to identified security incidents by executing defined response procedures.",["Implement containment procedures","Eradicate threats","Recover affected systems","Conduct post-incident review"],["IR procedures","Containment actions","Recovery records","Post-mortem reports"],["Uncontained breaches","Repeated incidents","Extended impact"],"high",{"nist_800_53":["IR-4","IR-6"],"iso_27001":["A.5.26"]},["CC7.3","CC7.5"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc8-1","SOC 2","Common Criteria","CC8","CC8.1","Change Management","The entity authorizes, designs, develops, configures, documents, tests, approves, and implements changes.",["Implement formal change process","Require testing before production","Document all changes","Maintain rollback procedures"],["Change requests","Test results","Approval records","Rollback plans"],["Unauthorized changes","System instability","Security regression"],"high",{"nist_800_53":["CM-3"],"iso_27001":["A.8.32"]},["CC7.1","CC8.2"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-cc9-2","SOC 2","Common Criteria","CC9","CC9.2","Vendor and Business Partner Risk","The entity assesses and manages risks associated with vendors and business partners.",["Conduct vendor assessments","Include security in contracts","Monitor vendor compliance","Define exit strategies"],["Vendor assessments","Contract clauses","Monitoring reports","Exit plans"],["Third-party breach","Supply chain risk","Data exposure"],"high",{"nist_800_53":["SA-9"],"iso_27001":["A.5.19"]},["CC9.1"],["https://www.aicpa.org/soc2"]),
ctrl("soc2-a1-2","SOC 2","Availability","A1","A1.2","Recovery Objectives","The entity maintains recovery objectives and tests backup and recovery procedures.",["Define RTO and RPO","Test recovery quarterly","Document recovery procedures","Validate backup integrity"],["RTO/RPO documentation","Test results","Recovery procedures","Backup validation"],["Extended downtime","Data loss","Business disruption"],"high",{"nist_800_53":["CP-9","CP-10"],"iso_27001":["A.8.13"]},["A1.1","A1.3"],["https://www.aicpa.org/soc2"]),
]

# ===================== PCI DSS 4.0 (15) =====================
PCI=[
ctrl("pci-1-1","PCI DSS 4.0","Network Security Controls","REQ-1","1.1","Install and Maintain Network Security Controls","Processes and mechanisms for installing and maintaining network security controls are defined and understood.",["Document firewall policies","Define allowed traffic flows","Review rules semi-annually","Implement change management for rules"],["Firewall policy","Rule review records","Network diagrams","Change logs"],["Unauthorized network access","Data breach"],"high",{"nist_800_53":["SC-7"],"iso_27001":["A.8.20"],"cis_v8":["4.4"]},["1.2","1.3","1.4"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-2-2","PCI DSS 4.0","Secure Configurations","REQ-2","2.2","System Components are Configured and Managed Securely","System components are configured and managed securely by applying industry-accepted hardening standards.",["Apply CIS benchmarks","Remove default accounts","Disable unnecessary services","Document configurations"],["Hardening standards","Configuration scans","Default account removal","Service inventory"],["Misconfigurations","Default credentials","Expanded attack surface"],"high",{"nist_800_53":["CM-6","CM-7"],"iso_27001":["A.8.9"],"cis_v8":["4.1"]},["2.1","2.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-3-4","PCI DSS 4.0","Protect Stored Account Data","REQ-3","3.4","Render PAN Unreadable Anywhere it is Stored","PAN is rendered unreadable anywhere it is stored using strong cryptography.",["Encrypt PAN with AES-256","Implement tokenization","Use one-way hashes where appropriate","Manage encryption keys securely"],["Encryption configuration","Tokenization system","Key management procedures","Storage scan results"],["Cardholder data exposure","Compliance violation"],"high",{"nist_800_53":["SC-28"],"iso_27001":["A.8.24"],"cis_v8":["3.11"]},["3.1","3.5","3.6"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-4-1","PCI DSS 4.0","Protect Data in Transit","REQ-4","4.1","Strong Cryptography Protects Cardholder Data During Transmission","Strong cryptography and security protocols protect cardholder data during transmission over open networks.",["Use TLS 1.2+ for all transmissions","Disable weak protocols","Implement certificate management","Monitor for downgrade attacks"],["TLS configuration","Protocol scan results","Certificate inventory","Monitoring records"],["Data interception","Man-in-the-middle","Eavesdropping"],"high",{"nist_800_53":["SC-8"],"iso_27001":["A.8.24"],"cis_v8":["3.10"]},["4.2"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-5-2","PCI DSS 4.0","Protect from Malicious Software","REQ-5","5.2","Malicious Software is Prevented or Detected and Addressed","Malicious software is prevented, or detected and addressed on all system components.",["Deploy anti-malware on all systems","Enable real-time scanning","Update signatures automatically","Perform periodic full scans"],["AV/EDR deployment records","Signature update logs","Scan schedules","Detection reports"],["Malware infection","Ransomware","Data theft"],"high",{"nist_800_53":["SI-3"],"iso_27001":["A.8.7"],"cis_v8":["10.1"]},["5.1","5.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-6-3","PCI DSS 4.0","Develop Secure Systems","REQ-6","6.3","Security Vulnerabilities are Identified and Addressed","Security vulnerabilities are identified and addressed in a timely manner.",["Implement patch management","Define SLAs (critical: 30 days)","Track remediation","Validate with re-scanning"],["Patch records","SLA compliance","Vulnerability tracking","Re-scan results"],["Exploitation of known vulnerabilities"],"high",{"nist_800_53":["SI-2","RA-5"],"iso_27001":["A.8.8"],"cis_v8":["7.1"]},["6.1","6.2"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-7-1","PCI DSS 4.0","Restrict Access","REQ-7","7.1","Access to System Components and Cardholder Data is Restricted","Access to system components and cardholder data is limited to only those individuals whose job requires such access.",["Implement need-to-know access","Define access by job function","Review access semi-annually","Document access decisions"],["Access control policy","Role definitions","Review records","Access matrices"],["Unauthorized data access","Insider threat","Compliance violation"],"high",{"nist_800_53":["AC-3","AC-6"],"iso_27001":["A.5.15"],"cis_v8":["3.3"]},["7.2","7.3"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-8-3","PCI DSS 4.0","Identify Users and Authenticate Access","REQ-8","8.3","Strong Authentication for Users and Administrators","Strong authentication for users and administrators is established and managed.",["Implement MFA for all admin access","Enforce password complexity","Implement account lockout","Use unique IDs for all users"],["MFA configuration","Password policy","Lockout settings","User ID inventory"],["Credential theft","Brute-force","Shared account abuse"],"high",{"nist_800_53":["IA-2","IA-5"],"iso_27001":["A.8.5"],"cis_v8":["5.2","6.3"]},["8.1","8.2","8.4"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-10-1","PCI DSS 4.0","Log and Monitor","REQ-10","10.1","Audit Trails are Implemented","Audit trails are implemented to link all access to system components to each individual user.",["Log all access to cardholder data","Include user ID, timestamp, action","Centralize logs","Protect log integrity"],["Logging configuration","Sample logs","SIEM setup","Log protection measures"],["Undetected breaches","Insufficient forensics","Non-compliance"],"high",{"nist_800_53":["AU-2","AU-3"],"iso_27001":["A.8.15"],"cis_v8":["8.2"]},["10.2","10.3","10.4"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-11-3","PCI DSS 4.0","Test Security","REQ-11","11.3","External and Internal Vulnerabilities are Regularly Identified and Addressed","External and internal vulnerabilities are regularly identified, prioritized, and addressed.",["Scan internally quarterly","Scan externally quarterly (ASV)","Remediate critical within 30 days","Rescan after remediation"],["Internal scan reports","ASV scan reports","Remediation records","Rescan results"],["Unpatched vulnerabilities","Compliance failure"],"high",{"nist_800_53":["RA-5"],"iso_27001":["A.8.8"],"cis_v8":["7.1","7.5"]},["11.1","11.4"],["https://www.pcisecuritystandards.org"]),
ctrl("pci-12-1","PCI DSS 4.0","Information Security Policy","REQ-12","12.1","Information Security Policy is Established","A comprehensive information security policy that governs and provides direction for protection of the entity's information assets.",["Establish security policy","Review annually","Communicate to all personnel","Address all PCI DSS requirements"],["Security policy","Review records","Communication records","Acknowledgments"],["Lack of direction","Inconsistent practices","Audit failure"],"high",{"nist_800_53":["PL-1","PL-2"],"iso_27001":["A.5.1"],"cis_v8":["N/A"]},["12.2","12.3"],["https://www.pcisecuritystandards.org"]),
]

# ===================== MORE RISKS (15) =====================
RISKS_NEW=[
{"id":"risk-privilege-escalation","name":"Privilege Escalation","category":"Access Control","description":"Attackers or insiders escalating from standard user to admin/root access.","threat_source":"External attacker, malicious insider","vulnerability":"Misconfigurations, unpatched systems, weak access controls","likelihood":3,"impact":5,"risk_score":15,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Implement least privilege","Patch systems regularly","Monitor privilege changes","Use PAM solutions"],"controls":["NIST AC-6","CIS 5.4","ISO A.5.15"],"kri":"Number of unauthorized privilege escalation attempts per month"},
{"id":"risk-supply-chain","name":"Supply Chain Attack","category":"Third Party","description":"Compromise through a trusted vendor's software update or service.","threat_source":"Nation-state, APT groups","vulnerability":"Trusted vendor relationships, auto-updates","likelihood":2,"impact":5,"risk_score":10,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Vendor security assessments","Software composition analysis","Monitor vendor security advisories","Implement zero-trust for vendor access"],"controls":["NIST SA-9","ISO A.5.19","CIS 15.1"],"kri":"% of critical vendors with completed security assessments"},
{"id":"risk-cloud-misconfig","name":"Cloud Storage Exposure","category":"Cloud Security","description":"Publicly accessible cloud storage (S3, Azure Blob) containing sensitive data.","threat_source":"Automated scanners, opportunistic attackers","vulnerability":"Default public access, misconfigured permissions","likelihood":4,"impact":4,"risk_score":16,"risk_level":"Critical","treatment":"Mitigate","treatment_plan":["Enable bucket-level access controls","Block public access by default","Scan for public buckets regularly","Implement CSPM tools"],"controls":["NIST AC-3","ISO A.5.23","CIS 3.3"],"kri":"Number of publicly accessible storage resources"},
{"id":"risk-shadow-it","name":"Shadow IT","category":"Asset Management","description":"Employees using unauthorized applications and services without IT knowledge.","threat_source":"Employees seeking convenience","vulnerability":"Lack of approved alternatives, no discovery tools","likelihood":4,"impact":3,"risk_score":12,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Deploy CASB","Provide approved alternatives","Educate employees","Monitor for unauthorized services"],"controls":["NIST CM-8","CIS 2.1","ISO A.5.9"],"kri":"Number of unauthorized SaaS applications discovered per quarter"},
{"id":"risk-dos-ddos","name":"Denial of Service (DDoS)","category":"Availability","description":"Distributed denial of service attacks overwhelming systems and causing outages.","threat_source":"Hacktivists, competitors, extortionists","vulnerability":"Insufficient capacity, no DDoS protection","likelihood":3,"impact":4,"risk_score":12,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Implement DDoS protection service","Configure rate limiting","Develop incident response for DDoS","Maintain redundant infrastructure"],"controls":["NIST SC-5","ISO A.8.20"],"kri":"Number of DDoS incidents per year and mean time to mitigate"},
{"id":"risk-api-exposure","name":"API Security Vulnerabilities","category":"Application Security","description":"Exposed or poorly secured APIs allowing unauthorized data access or manipulation.","threat_source":"External attackers, automated tools","vulnerability":"Broken authentication, excessive data exposure, injection","likelihood":4,"impact":4,"risk_score":16,"risk_level":"Critical","treatment":"Mitigate","treatment_plan":["Implement API gateway","Require authentication on all endpoints","Rate limiting","Regular API security testing"],"controls":["NIST AC-3","ISO A.8.25","CIS 16.1"],"kri":"Number of critical API vulnerabilities found per scan"},
{"id":"risk-data-retention","name":"Excessive Data Retention","category":"Data Protection","description":"Retaining personal or sensitive data beyond legal requirements, increasing breach impact.","threat_source":"Regulatory enforcement, data breach","vulnerability":"No retention policy, no automated deletion","likelihood":3,"impact":4,"risk_score":12,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Define retention schedules","Implement automated deletion","Classify data by retention requirements","Audit compliance quarterly"],"controls":["NIST MP-6","ISO A.5.12"],"kri":"Volume of data retained beyond policy requirements"},
{"id":"risk-byod","name":"BYOD Security","category":"Endpoint Security","description":"Personal devices accessing corporate data without adequate security controls.","threat_source":"Lost/stolen devices, malware on personal devices","vulnerability":"No MDM, no encryption, no remote wipe","likelihood":4,"impact":3,"risk_score":12,"risk_level":"High","treatment":"Mitigate","treatment_plan":["Implement MDM/MAM","Require device encryption","Enable remote wipe","Containerize corporate data"],"controls":["NIST AC-19","ISO A.8.1","CIS 4.1"],"kri":"% of BYOD devices enrolled in MDM"},
{"id":"risk-social-media","name":"Social Media Information Leakage","category":"Information Disclosure","description":"Employees inadvertently sharing sensitive information on social media platforms.","threat_source":"Employees, social engineering reconnaissance","vulnerability":"Lack of awareness, no social media policy","likelihood":3,"impact":3,"risk_score":9,"risk_level":"Medium","treatment":"Mitigate","treatment_plan":["Establish social media policy","Security awareness training","Monitor for data leaks","Implement DLP for social platforms"],"controls":["NIST AT-2","ISO A.6.3"],"kri":"Number of social media policy violations detected"},
{"id":"risk-legacy-systems","name":"Legacy System Vulnerabilities","category":"Technology","description":"End-of-life systems that no longer receive security patches.","threat_source":"Any attacker targeting known vulnerabilities","vulnerability":"No patches available, outdated protocols","likelihood":4,"impact":4,"risk_score":16,"risk_level":"Critical","treatment":"Mitigate","treatment_plan":["Isolate legacy systems","Implement compensating controls","Plan migration/replacement","Monitor heavily"],"controls":["NIST SI-2","ISO A.8.8","CIS 7.1"],"kri":"Number of EOL systems still in production"},
]

if __name__=="__main__":
    print("GRC Batch 4 — SOC 2 + PCI DSS + Risks...")
    # SOC 2
    data={"id":"soc2","name":"SOC 2","description":"Service Organization Control 2 — Trust Service Criteria","controls":SOC2}
    with open(OUTPUT_DIR/"soc2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  SOC 2: {len(SOC2)} controls")
    # PCI DSS
    data={"id":"pci-dss-4","name":"PCI DSS 4.0","description":"Payment Card Industry Data Security Standard v4.0","controls":PCI}
    with open(OUTPUT_DIR/"pci_dss.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  PCI DSS: {len(PCI)} controls")
    # Risks
    existing=[]
    rpath=RISK_DIR/"scenarios.json"
    if rpath.exists():
        with open(rpath) as f: existing=json.load(f)
    existing_ids={r["id"] for r in existing}
    for r in RISKS_NEW:
        if r["id"] not in existing_ids: existing.append(r)
    with open(rpath,'w') as f: json.dump(existing,f,indent=2)
    print(f"  Risks: {len(existing)} total")
    # Total controls
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
