#!/usr/bin/env python3
"""GRC Batch 2 — ISO 27001 controls."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== ISO 27001:2022 ANNEX A (30 controls) =====================
ISO=[
ctrl("iso-5-1","ISO 27001","Organizational Controls","A.5","A.5.1","Policies for Information Security","Management shall define, approve, publish, and communicate information security policies.",["Define information security policy","Get management approval","Communicate to all employees","Review annually"],["Approved policy document","Communication records","Review/approval history","Employee acknowledgments"],["Lack of direction","Inconsistent security practices"],"high",{"nist_800_53":["AC-1","AT-1","PL-1"],"cis_v8":["N/A"]},["A.5.2","A.5.3"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-3","ISO 27001","Organizational Controls","A.5","A.5.3","Segregation of Duties","Conflicting duties shall be segregated to reduce opportunities for unauthorized modification or misuse.",["Identify conflicting roles","Implement RBAC","Require dual authorization for critical changes","Document segregation matrix"],["Segregation matrix","Role definitions","Dual-control procedures"],["Fraud","Unauthorized changes","Collusion"],"high",{"nist_800_53":["AC-5"],"cis_v8":["6.8"]},["A.5.15","A.5.16"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-7","ISO 27001","Organizational Controls","A.5","A.5.7","Threat Intelligence","Information about threats shall be collected and analyzed to produce threat intelligence.",["Subscribe to threat feeds","Participate in ISACs","Analyze threats relevant to organization","Share intelligence with peers"],["Threat intelligence reports","Feed subscriptions","Analysis documents","Sharing agreements"],["Unknown threats","Delayed response to emerging attacks"],"medium",{"nist_800_53":["RA-3","PM-16"],"cis_v8":["N/A"]},["A.5.24","A.8.8"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-9","ISO 27001","Organizational Controls","A.5","A.5.9","Inventory of Information and Other Associated Assets","An inventory of information and associated assets shall be identified and maintained.",["Maintain asset register","Classify assets by criticality","Assign owners","Update on changes"],["Asset inventory","Classification records","Owner assignments","Update logs"],["Unknown assets","Shadow IT","Unmanaged risk"],"high",{"nist_800_53":["CM-8"],"cis_v8":["1.1","1.2","2.1"]},["A.5.10","A.5.12"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-10","ISO 27001","Organizational Controls","A.5","A.5.10","Acceptable Use of Information and Other Associated Assets","Rules for acceptable use of information and assets shall be identified and documented.",["Define acceptable use policy","Cover email, internet, mobile devices","Include consequences of violation","Get employee acknowledgment"],["Acceptable use policy","Acknowledgment records","Violation reports"],["Misuse of resources","Legal liability","Data exposure"],"medium",{"nist_800_53":["PL-4"],"cis_v8":["N/A"]},["A.5.9","A.5.12"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-12","ISO 27001","Organizational Controls","A.5","A.5.12","Classification of Information","Information shall be classified according to information security needs based on confidentiality, integrity, and availability.",["Define classification levels (Public, Internal, Confidential, Restricted)","Label all information assets","Define handling procedures per level","Train employees on classification"],["Classification policy","Labeled documents","Handling procedures","Training records"],["Data exposure","Inappropriate handling","Compliance violations"],"high",{"nist_800_53":["RA-2"],"cis_v8":["3.7"]},["A.5.9","A.5.13"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-15","ISO 27001","Organizational Controls","A.5","A.5.15","Access Control","Rules to control physical and logical access to information shall be established based on business and security requirements.",["Implement role-based access","Apply least privilege","Review access quarterly","Require formal access requests"],["Access control policy","RBAC configuration","Access review records","Request/approval forms"],["Unauthorized access","Privilege creep","Data breach"],"high",{"nist_800_53":["AC-1","AC-2","AC-3"],"cis_v8":["5.1","6.1"]},["A.5.16","A.5.18","A.8.3"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-16","ISO 27001","Organizational Controls","A.5","A.5.16","Identity Management","The full lifecycle of identities shall be managed.",["Unique identifiers for all users","Disable accounts on termination","Review identities periodically","Manage service accounts separately"],["Identity lifecycle procedures","Termination checklists","Review records","Service account inventory"],["Orphaned accounts","Identity theft","Unauthorized access"],"high",{"nist_800_53":["IA-2","IA-4"],"cis_v8":["5.1","5.2"]},["A.5.15","A.5.17","A.5.18"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-17","ISO 27001","Organizational Controls","A.5","A.5.17","Authentication Information","Allocation and management of authentication information shall be controlled.",["Enforce strong passwords","Implement MFA","Protect credential storage","Rotate service account passwords"],["Password policy","MFA enrollment","Credential management procedures"],["Credential compromise","Brute-force attacks"],"high",{"nist_800_53":["IA-5"],"cis_v8":["5.2","5.3"]},["A.5.15","A.5.16"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-19","ISO 27001","Organizational Controls","A.5","A.5.19","Information Security in Supplier Relationships","Processes shall be defined to manage information security risks associated with suppliers.",["Assess supplier security posture","Include security in contracts","Monitor supplier compliance","Define data handling requirements"],["Vendor assessments","Contract security clauses","Monitoring reports","Data processing agreements"],["Supply chain compromise","Third-party breach","Data exposure"],"high",{"nist_800_53":["SA-9","SR-1"],"cis_v8":["15.1","15.2"]},["A.5.20","A.5.21","A.5.22"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-23","ISO 27001","Organizational Controls","A.5","A.5.23","Information Security for Use of Cloud Services","Processes for acquisition, use, management, and exit from cloud services shall be established.",["Define cloud security requirements","Assess cloud provider security","Implement shared responsibility model","Plan for cloud exit"],["Cloud security policy","Provider assessments","Shared responsibility documentation","Exit strategy"],["Cloud misconfiguration","Data sovereignty issues","Vendor lock-in"],"high",{"nist_800_53":["SA-9"],"cis_v8":["N/A"]},["A.5.19","A.5.21"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-24","ISO 27001","Organizational Controls","A.5","A.5.24","Information Security Incident Management Planning and Preparation","The organization shall plan and prepare for managing information security incidents.",["Develop incident response plan","Define roles and responsibilities","Establish communication procedures","Conduct regular exercises"],["IR plan","Role assignments","Communication templates","Exercise reports"],["Delayed response","Uncoordinated handling","Regulatory non-compliance"],"high",{"nist_800_53":["IR-1","IR-8"],"cis_v8":["17.1","17.2","17.3"]},["A.5.25","A.5.26","A.5.27"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-29","ISO 27001","Organizational Controls","A.5","A.5.29","Information Security During Disruption","The organization shall plan how to maintain information security during disruption.",["Include security in BCP","Maintain security controls during incidents","Test continuity of security measures","Define minimum security requirements during disruption"],["BCP with security requirements","Test results","Minimum security standards"],["Security gaps during incidents","Exploitation during disruption"],"high",{"nist_800_53":["CP-2","CP-4"],"cis_v8":["N/A"]},["A.5.24","A.5.30"],["https://www.iso.org/standard/27001"]),
ctrl("iso-5-35","ISO 27001","Organizational Controls","A.5","A.5.35","Independent Review of Information Security","The organization's approach to managing information security shall be independently reviewed.",["Conduct annual independent audits","Use qualified assessors","Address findings with action plans","Report results to management"],["Audit reports","Assessor qualifications","Action plans","Management review minutes"],["Unidentified weaknesses","False sense of security","Compliance gaps"],"high",{"nist_800_53":["CA-2","CA-7"],"cis_v8":["18.1","18.2"]},["A.5.36"],["https://www.iso.org/standard/27001"]),
ctrl("iso-6-1","ISO 27001","People Controls","A.6","A.6.1","Screening","Background verification checks on candidates shall be carried out prior to joining.",["Conduct background checks","Verify qualifications","Check references","Re-screen for sensitive roles"],["Screening policy","Background check records","Verification results"],["Insider threat","Unvetted personnel","Fraud"],"high",{"nist_800_53":["PS-3"],"cis_v8":["N/A"]},["A.6.2","A.6.5"],["https://www.iso.org/standard/27001"]),
ctrl("iso-6-3","ISO 27001","People Controls","A.6","A.6.3","Information Security Awareness, Education and Training","Personnel shall receive appropriate security awareness education and training.",["Provide annual awareness training","Conduct phishing simulations","Role-based training for IT/security","Track completion and effectiveness"],["Training records","Simulation results","Completion rates","Effectiveness metrics"],["Human error","Phishing susceptibility","Policy violations"],"high",{"nist_800_53":["AT-2","AT-3"],"cis_v8":["14.1","14.2","14.3"]},["A.6.1","A.6.4"],["https://www.iso.org/standard/27001"]),
ctrl("iso-7-1","ISO 27001","Physical Controls","A.7","A.7.1","Physical Security Perimeters","Security perimeters shall be defined and used to protect areas containing information.",["Define security zones","Implement physical barriers","Control entry points","Monitor perimeters"],["Zone definitions","Physical security plans","Access control systems","Monitoring records"],["Unauthorized physical access","Theft","Sabotage"],"high",{"nist_800_53":["PE-3"],"cis_v8":["N/A"]},["A.7.2","A.7.3","A.7.4"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-1","ISO 27001","Technological Controls","A.8","A.8.1","User Endpoint Devices","Information stored on, processed by, or accessible via user endpoint devices shall be protected.",["Implement endpoint protection (EDR)","Enable full-disk encryption","Apply security baselines","Manage via MDM"],["EDR deployment records","Encryption status","Baseline compliance","MDM enrollment"],["Data theft from lost devices","Malware infection","Unauthorized access"],"high",{"nist_800_53":["SC-28","CM-6"],"cis_v8":["4.1","10.1"]},["A.8.5","A.8.7"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-5","ISO 27001","Technological Controls","A.8","A.8.5","Secure Authentication","Secure authentication technologies and procedures shall be established.",["Implement MFA for all remote access","Use certificate-based auth where possible","Enforce strong password policies","Implement SSO with MFA"],["MFA configuration","Authentication architecture","Password policy settings","SSO implementation"],["Credential theft","Unauthorized access","Account compromise"],"high",{"nist_800_53":["IA-2","IA-5"],"cis_v8":["5.2","6.3","6.4"]},["A.5.16","A.5.17","A.8.3"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-7","ISO 27001","Technological Controls","A.8","A.8.7","Protection Against Malware","Protection against malware shall be implemented and supported by user awareness.",["Deploy EDR/AV on all endpoints","Enable real-time protection","Update signatures automatically","Educate users on malware risks"],["EDR deployment records","Update logs","Scan results","User training records"],["Malware infection","Ransomware","Data theft"],"high",{"nist_800_53":["SI-3"],"cis_v8":["10.1","10.2","10.3"]},["A.8.1","A.6.3"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-8","ISO 27001","Technological Controls","A.8","A.8.8","Management of Technical Vulnerabilities","Information about technical vulnerabilities shall be obtained, evaluated, and appropriate measures taken.",["Implement vulnerability scanning","Define remediation SLAs","Track patch compliance","Conduct penetration testing"],["Scan reports","Remediation records","SLA metrics","Pentest reports"],["Exploitation of known vulnerabilities","Compliance gaps"],"high",{"nist_800_53":["RA-5","SI-2"],"cis_v8":["7.1","7.2","7.5"]},["A.8.9","A.5.7"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-9","ISO 27001","Technological Controls","A.8","A.8.9","Configuration Management","Configurations including security configurations shall be established, documented, and managed.",["Define security baselines","Use CIS benchmarks","Scan for compliance","Manage changes formally"],["Baseline documentation","Compliance scan results","Change records","Deviation approvals"],["Misconfigurations","Drift from secure state","Unauthorized changes"],"high",{"nist_800_53":["CM-2","CM-6"],"cis_v8":["4.1","4.2"]},["A.8.8","A.8.32"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-13","ISO 27001","Technological Controls","A.8","A.8.13","Information Backup","Backup copies of information, software, and systems shall be maintained and regularly tested.",["Implement 3-2-1 backup strategy","Test restoration monthly","Encrypt backups","Store offsite copies"],["Backup schedules","Test results","Encryption records","Offsite storage"],["Data loss","Ransomware impact","Business disruption"],"high",{"nist_800_53":["CP-9"],"cis_v8":["11.1","11.2","11.3"]},["A.8.14","A.5.29"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-15","ISO 27001","Technological Controls","A.8","A.8.15","Logging","Logs that record activities, exceptions, faults, and other relevant events shall be produced and protected.",["Define logging requirements","Centralize logs in SIEM","Protect log integrity","Retain logs per policy"],["Logging configuration","SIEM architecture","Retention policy","Log access controls"],["Undetected incidents","Insufficient forensic evidence"],"high",{"nist_800_53":["AU-2","AU-3","AU-9"],"cis_v8":["8.2","8.5","8.9"]},["A.8.16","A.8.17"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-20","ISO 27001","Technological Controls","A.8","A.8.20","Networks Security","Networks and network devices shall be managed and controlled to protect information.",["Segment networks by sensitivity","Implement firewalls","Monitor network traffic","Restrict management access"],["Network diagrams","Firewall rules","Monitoring configuration","Access controls"],["Lateral movement","Unauthorized access","Data exfiltration"],"high",{"nist_800_53":["SC-7"],"cis_v8":["4.4","13.1"]},["A.8.21","A.8.22","A.8.23"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-24","ISO 27001","Technological Controls","A.8","A.8.24","Use of Cryptography","Rules for effective use of cryptography including key management shall be defined.",["Define cryptographic standards","Use approved algorithms (AES-256, RSA-2048+)","Implement key management lifecycle","Protect key storage"],["Cryptographic policy","Algorithm standards","Key management procedures","Key storage configuration"],["Data exposure","Weak encryption","Key compromise"],"high",{"nist_800_53":["SC-13","SC-12"],"cis_v8":["3.11"]},["A.8.20","A.5.12"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-25","ISO 27001","Technological Controls","A.8","A.8.25","Secure Development Life Cycle","Rules for secure development of software and systems shall be established.",["Implement SSDLC","Conduct code reviews","Perform SAST/DAST","Train developers on secure coding"],["SSDLC documentation","Code review records","Scan results","Training records"],["Software vulnerabilities","Insecure code","Exploitation"],"high",{"nist_800_53":["SA-3","SA-11"],"cis_v8":["16.1","16.2"]},["A.8.26","A.8.28","A.8.31"],["https://www.iso.org/standard/27001"]),
ctrl("iso-8-28","ISO 27001","Technological Controls","A.8","A.8.28","Secure Coding","Secure coding principles shall be applied to software development.",["Follow OWASP guidelines","Use parameterized queries","Implement input validation","Apply output encoding"],["Coding standards","OWASP compliance checks","Code review findings","SAST results"],["Injection vulnerabilities","XSS","Buffer overflows"],"high",{"nist_800_53":["SA-11","SI-10"],"cis_v8":["16.12"]},["A.8.25","A.8.29"],["https://www.iso.org/standard/27001"]),
]

if __name__=="__main__":
    print("GRC Batch 2 — ISO 27001...")
    data = {"id":"iso-27001","name":"ISO 27001:2022","description":"Information Security Management System — Annex A Controls","controls":ISO}
    path = OUTPUT_DIR / "iso_27001.json"
    with open(path,'w') as f: json.dump(data,f,indent=2)
    print(f"  ISO 27001: {len(ISO)} controls")
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
