#!/usr/bin/env python3
"""GRC Batch 5 — push to 200. More NIST + ISO + CIS + GDPR."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "frameworks"

def ctrl(id,fw,family,fid,cid,name,desc,guidance,evidence,risks,priority,mappings,related,refs):
    return {"id":id,"framework":fw,"family":family,"family_id":fid,"control_id":cid,"name":name,"description":desc,"implementation_guidance":guidance,"audit_evidence":evidence,"risk_addressed":risks,"priority":priority,"mappings":mappings,"related_controls":related,"references":refs}

# ===================== MORE NIST (20) =====================
NIST5=[
ctrl("nist-ac-14","NIST 800-53","Access Control","AC","AC-14","Permitted Actions Without Identification","Identify specific user actions that can be performed without identification or authentication.",["Document public-facing actions","Limit anonymous access to minimum","Monitor anonymous usage","Review periodically"],["Anonymous access documentation","Usage logs","Review records"],["Unauthorized anonymous access"],"medium",{"iso_27001":["A.5.15"],"cis_v8":["N/A"]},["AC-2","AC-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-18","NIST 800-53","Access Control","AC","AC-18","Wireless Access","Establish usage restrictions and implementation guidance for wireless access.",["Require WPA3/WPA2-Enterprise","Implement 802.1X","Separate guest WiFi","Monitor rogue APs"],["Wireless policy","802.1X configuration","WIDS alerts","Guest network isolation"],["Unauthorized wireless access","Rogue access points","Eavesdropping"],"high",{"iso_27001":["A.8.20"],"cis_v8":["N/A"]},["AC-17","SC-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ac-19","NIST 800-53","Access Control","AC","AC-19","Access Control for Mobile Devices","Establish usage restrictions for organization-controlled mobile devices.",["Implement MDM","Require device encryption","Enable remote wipe","Enforce screen lock"],["MDM enrollment","Encryption status","Remote wipe capability","Policy compliance"],["Data loss from lost devices","Unauthorized mobile access"],"high",{"iso_27001":["A.8.1"],"cis_v8":["N/A"]},["AC-3","AC-17","MP-7"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-au-12","NIST 800-53","Audit and Accountability","AU","AU-12","Audit Record Generation","Provide audit record generation capability for auditable events on all system components.",["Configure logging on all systems","Include all defined auditable events","Ensure log generation cannot be disabled by users","Synchronize timestamps"],["Logging configuration","Event coverage verification","NTP configuration","Log generation testing"],["Missing audit trail","Incomplete evidence"],"high",{"iso_27001":["A.8.15"],"cis_v8":["8.2","8.5"]},["AU-2","AU-3","AU-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ca-7","NIST 800-53","Assessment, Authorization, and Monitoring","CA","CA-7","Continuous Monitoring","Develop a continuous monitoring strategy and implement a continuous monitoring program.",["Define monitoring metrics","Automate data collection","Report to management monthly","Adjust strategy based on findings"],["Monitoring strategy","Automated dashboards","Monthly reports","Strategy updates"],["Degraded security posture","Undetected changes"],"high",{"iso_27001":["A.8.16"],"cis_v8":["N/A"]},["CA-2","SI-4","RA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cm-5","NIST 800-53","Configuration Management","CM","CM-5","Access Restrictions for Change","Define and enforce physical and logical access restrictions for changes to systems.",["Restrict change access to authorized personnel","Implement approval workflows","Log all changes","Separate development and production"],["Change access controls","Approval records","Change logs","Environment separation"],["Unauthorized changes","Malicious modifications"],"high",{"iso_27001":["A.8.32"],"cis_v8":["4.1"]},["CM-3","AC-3","AC-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cp-2","NIST 800-53","Contingency Planning","CP","CP-2","Contingency Plan","Develop a contingency plan that addresses roles, responsibilities, and recovery procedures.",["Define essential functions","Identify recovery priorities","Document procedures","Distribute to key personnel"],["Contingency plan","Distribution records","Role assignments","Recovery priorities"],["Extended outages","Uncoordinated recovery","Business disruption"],"high",{"iso_27001":["A.5.29","A.5.30"],"cis_v8":["N/A"]},["CP-3","CP-4","CP-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-cp-4","NIST 800-53","Contingency Planning","CP","CP-4","Contingency Plan Testing","Test the contingency plan to determine effectiveness and organizational readiness.",["Test annually at minimum","Include tabletop and functional exercises","Document results and lessons learned","Update plan based on findings"],["Test plans","Exercise results","Lessons learned","Plan updates"],["Untested recovery procedures","Unknown gaps"],"high",{"iso_27001":["A.5.29"],"cis_v8":["N/A"]},["CP-2","CP-3","CP-9"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ia-4","NIST 800-53","Identification and Authentication","IA","IA-4","Identifier Management","Manage system identifiers by receiving authorization, assigning, and preventing reuse.",["Assign unique identifiers","Prevent identifier reuse","Disable inactive identifiers after 30 days","Maintain identifier registry"],["Identifier assignment procedures","Inactive account reports","Registry documentation"],["Shared accounts","Orphaned identifiers","Accountability gaps"],"high",{"iso_27001":["A.5.16"],"cis_v8":["5.1"]},["IA-2","IA-5","AC-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-2","NIST 800-53","Incident Response","IR","IR-2","Incident Response Training","Provide incident response training to personnel consistent with assigned roles.",["Train IR team on procedures","Conduct tabletop exercises","Include technical and communication skills","Update training on plan changes"],["Training records","Exercise participation","Skill assessments","Training materials"],["Ineffective response","Untrained personnel"],"high",{"iso_27001":["A.5.24"],"cis_v8":["17.1"]},["IR-1","IR-3","IR-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ir-8","NIST 800-53","Incident Response","IR","IR-8","Incident Response Plan","Develop an incident response plan that provides a roadmap for implementing the IR capability.",["Define incident types and severity","Establish communication procedures","Include escalation paths","Define metrics and reporting"],["IR plan document","Communication templates","Escalation matrix","Metrics definitions"],["Uncoordinated response","Communication failures"],"high",{"iso_27001":["A.5.24"],"cis_v8":["17.1","17.2"]},["IR-1","IR-4","IR-6"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ma-2","NIST 800-53","Maintenance","MA","MA-2","Controlled Maintenance","Schedule, document, and review records of maintenance and repairs on system components.",["Schedule preventive maintenance","Document all maintenance activities","Require authorization for maintenance","Supervise external maintenance personnel"],["Maintenance schedules","Work orders","Authorization records","Supervision logs"],["System failures","Unauthorized access during maintenance"],"medium",{"iso_27001":["A.7.13"],"cis_v8":["N/A"]},["MA-3","MA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-mp-2","NIST 800-53","Media Protection","MP","MP-2","Media Access","Restrict access to digital and non-digital media to authorized individuals.",["Control access to backup media","Secure media storage areas","Log media access","Implement media tracking"],["Media access logs","Storage security","Tracking records"],["Unauthorized data access","Media theft"],"medium",{"iso_27001":["A.7.10"],"cis_v8":["3.1"]},["MP-4","MP-6","PE-3"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pe-6","NIST 800-53","Physical and Environmental Protection","PE","PE-6","Monitoring Physical Access","Monitor physical access to facilities to detect and respond to physical security incidents.",["Deploy security cameras","Monitor access logs","Alert on unauthorized access attempts","Review footage periodically"],["Camera system","Access logs","Alert records","Review schedules"],["Undetected physical intrusion","Tailgating"],"high",{"iso_27001":["A.7.2","A.7.4"],"cis_v8":["N/A"]},["PE-3","PE-8"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-pm-9","NIST 800-53","Program Management","PM","PM-9","Risk Management Strategy","Develop a comprehensive strategy to manage risk to organizational operations.",["Define risk tolerance","Establish risk assessment methodology","Integrate risk into decision-making","Report risk to leadership"],["Risk management strategy","Risk tolerance statement","Methodology documentation","Leadership reports"],["Unmanaged risk","Inconsistent risk decisions"],"high",{"iso_27001":["A.5.7"],"cis_v8":["N/A"]},["RA-3","PM-28"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-ps-4","NIST 800-53","Personnel Security","PS","PS-4","Personnel Termination","Upon termination, disable access, retrieve assets, and conduct exit interviews.",["Disable all access within 24 hours","Retrieve badges, laptops, tokens","Conduct exit interview","Notify relevant parties"],["Termination checklists","Access disable records","Asset return records","Exit interview notes"],["Continued access after termination","Data theft on departure"],"high",{"iso_27001":["A.6.5"],"cis_v8":["N/A"]},["PS-5","AC-2"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sa-4","NIST 800-53","System and Services Acquisition","SA","SA-4","Acquisition Process","Include security requirements in system acquisition contracts.",["Define security requirements in RFPs","Require vendor security documentation","Include right-to-audit clauses","Define acceptance criteria"],["RFP security requirements","Vendor documentation","Contract clauses","Acceptance testing"],["Insecure products","Missing security features"],"high",{"iso_27001":["A.5.19","A.5.20"],"cis_v8":["N/A"]},["SA-9","SR-1"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-sc-5","NIST 800-53","System and Communications Protection","SC","SC-5","Denial-of-Service Protection","Protect against or limit the effects of denial-of-service attacks.",["Implement DDoS protection","Configure rate limiting","Deploy CDN","Maintain excess capacity"],["DDoS protection configuration","Rate limiting rules","CDN setup","Capacity planning"],["Service unavailability","Business disruption"],"high",{"iso_27001":["A.8.20"],"cis_v8":["N/A"]},["SC-7","SI-4"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-si-5","NIST 800-53","System and Information Integrity","SI","SI-5","Security Alerts, Advisories, and Directives","Receive and disseminate security alerts, advisories, and directives from external organizations.",["Subscribe to CISA alerts","Monitor vendor advisories","Distribute relevant alerts internally","Track response to directives"],["Alert subscriptions","Distribution records","Response tracking","Advisory review logs"],["Missed critical advisories","Delayed patching"],"medium",{"iso_27001":["A.5.7"],"cis_v8":["7.1"]},["SI-2","RA-5"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
ctrl("nist-si-10","NIST 800-53","System and Information Integrity","SI","SI-10","Information Input Validation","Check the validity of information inputs to the system.",["Implement input validation on all forms","Use allowlists over denylists","Validate data types and ranges","Sanitize special characters"],["Input validation rules","Code review findings","SAST results","WAF configuration"],["Injection attacks","Data corruption","Application compromise"],"high",{"iso_27001":["A.8.28"],"cis_v8":["16.12"]},["SI-3","SA-11"],["https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"]),
]

# ===================== GDPR (15) =====================
GDPR=[
ctrl("gdpr-art-5","GDPR","Principles","ART","Art.5","Principles Relating to Processing of Personal Data","Personal data shall be processed lawfully, fairly, transparently, with purpose limitation, data minimization, accuracy, storage limitation, and integrity.",["Define lawful basis for each processing activity","Implement data minimization","Set retention periods","Ensure accuracy of data"],["Processing register","Lawful basis documentation","Retention schedules","Data quality procedures"],["Regulatory fines","Reputational damage","Individual harm"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["Art.6","Art.13"],["https://gdpr-info.eu/art-5-gdpr/"]),
ctrl("gdpr-art-6","GDPR","Lawfulness","ART","Art.6","Lawfulness of Processing","Processing shall be lawful only if at least one legal basis applies (consent, contract, legal obligation, vital interests, public task, legitimate interests).",["Identify lawful basis for each activity","Document basis in processing register","Obtain consent where required","Conduct legitimate interest assessments"],["Processing register","Consent records","LIA documentation","Legal basis mapping"],["Unlawful processing","Regulatory fines"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["Art.5","Art.7","Art.9"],["https://gdpr-info.eu/art-6-gdpr/"]),
ctrl("gdpr-art-13","GDPR","Transparency","ART","Art.13","Information to be Provided to Data Subjects","When collecting personal data, provide identity of controller, purposes, legal basis, recipients, retention period, and rights.",["Create privacy notices","Include all required information","Make easily accessible","Update when processing changes"],["Privacy notices","Website privacy policy","Collection point notices","Update records"],["Transparency violations","Regulatory fines","Trust erosion"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["Art.14","Art.5"],["https://gdpr-info.eu/art-13-gdpr/"]),
ctrl("gdpr-art-15","GDPR","Data Subject Rights","ART","Art.15","Right of Access","Data subjects have the right to obtain confirmation of processing and access to their personal data.",["Implement subject access request (SAR) process","Respond within 30 days","Verify identity before disclosure","Provide data in common format"],["SAR procedures","Response records","Identity verification","Data export capability"],["Regulatory fines","Complaints to supervisory authority"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["Art.16","Art.17","Art.20"],["https://gdpr-info.eu/art-15-gdpr/"]),
ctrl("gdpr-art-17","GDPR","Data Subject Rights","ART","Art.17","Right to Erasure (Right to be Forgotten)","Data subjects have the right to obtain erasure of personal data without undue delay.",["Implement deletion procedures","Define exceptions (legal obligations)","Verify identity","Confirm deletion to subject"],["Deletion procedures","Request records","Confirmation records","Exception documentation"],["Regulatory fines","Continued processing of deleted data"],"high",{"nist_800_53":["MP-6"],"iso_27001":["A.5.12"]},["Art.15","Art.16"],["https://gdpr-info.eu/art-17-gdpr/"]),
ctrl("gdpr-art-25","GDPR","Data Protection by Design","ART","Art.25","Data Protection by Design and by Default","Implement appropriate technical and organizational measures to implement data protection principles.",["Privacy impact assessments for new projects","Minimize data collection by default","Implement pseudonymization","Build privacy into system design"],["DPIA records","Design documentation","Default settings","Privacy architecture"],["Privacy violations","Excessive data collection"],"high",{"nist_800_53":["SA-8"],"iso_27001":["A.5.12"]},["Art.5","Art.35"],["https://gdpr-info.eu/art-25-gdpr/"]),
ctrl("gdpr-art-28","GDPR","Processors","ART","Art.28","Processor","Processing by a processor shall be governed by a contract that sets out the subject-matter, duration, nature, and purpose of processing.",["Execute data processing agreements","Define processor obligations","Include audit rights","Specify sub-processor requirements"],["Data processing agreements","Processor list","Audit records","Sub-processor approvals"],["Unauthorized processing","Lack of accountability"],"high",{"nist_800_53":["SA-9"],"iso_27001":["A.5.19"]},["Art.29","Art.32"],["https://gdpr-info.eu/art-28-gdpr/"]),
ctrl("gdpr-art-30","GDPR","Records","ART","Art.30","Records of Processing Activities","Maintain a record of processing activities under its responsibility.",["Document all processing activities","Include purposes, categories, recipients","Record retention periods","Keep records up to date"],["Records of processing activities (ROPA)","Processing register","Update logs"],["Regulatory fines","Inability to demonstrate compliance"],"high",{"nist_800_53":["N/A"],"iso_27001":["A.5.12"]},["Art.5","Art.28"],["https://gdpr-info.eu/art-30-gdpr/"]),
ctrl("gdpr-art-32","GDPR","Security","ART","Art.32","Security of Processing","Implement appropriate technical and organizational measures to ensure security appropriate to the risk.",["Implement encryption","Ensure confidentiality, integrity, availability","Regular testing and evaluation","Pseudonymization where appropriate"],["Security measures documentation","Testing records","Risk assessments","Encryption configuration"],["Data breach","Unauthorized access","Regulatory fines"],"high",{"nist_800_53":["SC-8","SC-28"],"iso_27001":["A.8.24"]},["Art.5","Art.33","Art.34"],["https://gdpr-info.eu/art-32-gdpr/"]),
ctrl("gdpr-art-33","GDPR","Breach Notification","ART","Art.33","Notification of Personal Data Breach to Supervisory Authority","Notify supervisory authority within 72 hours of becoming aware of a personal data breach.",["Establish breach detection procedures","Define 72-hour notification process","Document breach details","Assess risk to individuals"],["Breach notification procedures","Notification records","Breach register","Risk assessments"],["Regulatory fines (up to 4% revenue)","Delayed notification penalties"],"high",{"nist_800_53":["IR-6"],"iso_27001":["A.5.24","A.6.8"]},["Art.34","Art.32"],["https://gdpr-info.eu/art-33-gdpr/"]),
ctrl("gdpr-art-35","GDPR","Impact Assessment","ART","Art.35","Data Protection Impact Assessment","Carry out DPIA where processing is likely to result in high risk to rights and freedoms.",["Identify high-risk processing","Conduct DPIA before processing","Consult DPO","Document assessment and mitigations"],["DPIA reports","Risk assessments","DPO consultation records","Mitigation plans"],["High-risk processing without assessment","Regulatory enforcement"],"high",{"nist_800_53":["RA-3"],"iso_27001":["A.5.7"]},["Art.25","Art.36"],["https://gdpr-info.eu/art-35-gdpr/"]),
]

# ===================== MORE CIS (15) =====================
CIS5=[
ctrl("cis-3-1","CIS Controls v8","Data Protection","CIS-3","3.1","Establish and Maintain a Data Management Process","Establish and maintain a data management process addressing data sensitivity, owner, handling, retention, and disposal.",["Define data classification scheme","Assign data owners","Document handling procedures","Define retention and disposal"],["Data management policy","Classification scheme","Owner assignments","Retention schedules"],["Data mishandling","Compliance violations","Data exposure"],"high",{"nist_800_53":["RA-2"],"iso_27001":["A.5.12"]},["3.2","3.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-3-10","CIS Controls v8","Data Protection","CIS-3","3.10","Encrypt Sensitive Data in Transit","Encrypt sensitive data in transit using TLS 1.2+ or equivalent.",["Enforce TLS 1.2+ on all services","Disable SSLv3, TLS 1.0, TLS 1.1","Implement HSTS","Monitor for downgrade attacks"],["TLS configuration","Protocol scan results","HSTS headers","Certificate management"],["Data interception","Man-in-the-middle"],"high",{"nist_800_53":["SC-8"],"iso_27001":["A.8.24"]},["3.11","3.12"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-4-4","CIS Controls v8","Secure Configuration","CIS-4","4.4","Implement and Manage a Firewall on Servers","Implement and manage a host-based firewall on servers with deny-all default.",["Configure host firewalls on all servers","Default deny inbound","Allow only required ports","Log denied connections"],["Firewall configuration","Rule documentation","Denied connection logs"],["Unauthorized network access","Lateral movement"],"high",{"nist_800_53":["SC-7"],"iso_27001":["A.8.20"]},["4.1","4.5"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-5-2","CIS Controls v8","Account Management","CIS-5","5.2","Use Unique Passwords","Use unique passwords for all enterprise assets where MFA is not supported.",["Enforce password uniqueness","Check against breach databases","Implement password managers","Minimum 14 characters"],["Password policy","Breach database checking","Password manager deployment"],["Credential stuffing","Password reuse attacks"],"high",{"nist_800_53":["IA-5"],"iso_27001":["A.5.17"]},["5.1","5.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-6-8","CIS Controls v8","Access Control Management","CIS-6","6.8","Define and Maintain Role-Based Access Control","Define and maintain role-based access control by determining and documenting access rights.",["Define roles based on job functions","Map permissions to roles","Review role assignments quarterly","Remove unnecessary permissions"],["Role definitions","Permission mappings","Review records","Change logs"],["Excessive access","Privilege creep","Insider threat"],"high",{"nist_800_53":["AC-2","AC-3"],"iso_27001":["A.5.15"]},["6.1","6.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-7-5","CIS Controls v8","Continuous Vulnerability Management","CIS-7","7.5","Perform Automated Vulnerability Scans of Internal Enterprise Assets","Perform automated vulnerability scans of internal assets on a quarterly basis at minimum.",["Deploy internal vulnerability scanner","Scan quarterly minimum","Authenticate scans for better coverage","Track remediation"],["Scan schedules","Scan reports","Remediation tracking","Coverage metrics"],["Unpatched internal vulnerabilities"],"high",{"nist_800_53":["RA-5"],"iso_27001":["A.8.8"]},["7.1","7.2","7.6"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-8-5","CIS Controls v8","Audit Log Management","CIS-8","8.5","Collect Detailed Audit Logs","Collect detailed audit logs including source, destination, timestamps, and user information.",["Configure detailed logging","Include all required fields","Forward to SIEM","Validate completeness"],["Log format standards","Sample detailed logs","SIEM ingestion","Completeness checks"],["Insufficient forensic detail","Incomplete investigations"],"high",{"nist_800_53":["AU-3"],"iso_27001":["A.8.15"]},["8.2","8.9"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-8-9","CIS Controls v8","Audit Log Management","CIS-8","8.9","Centralize Audit Logs","Centralize audit logs for correlation and analysis.",["Deploy central SIEM","Forward all logs","Implement correlation rules","Protect log integrity"],["SIEM architecture","Log source inventory","Correlation rules","Integrity controls"],["Fragmented visibility","Missed correlations"],"high",{"nist_800_53":["AU-6","AU-9"],"iso_27001":["A.8.15"]},["8.2","8.5","8.11"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-11-3","CIS Controls v8","Data Recovery","CIS-11","11.3","Protect Recovery Data","Protect recovery data with equivalent controls as the original data.",["Encrypt backups","Restrict backup access","Store offsite securely","Test backup integrity"],["Backup encryption","Access controls","Offsite storage","Integrity verification"],["Backup compromise","Data theft from backups"],"high",{"nist_800_53":["CP-9"],"iso_27001":["A.8.13"]},["11.1","11.2"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-12-1","CIS Controls v8","Network Infrastructure Management","CIS-12","12.1","Ensure Network Infrastructure is Up-to-Date","Ensure network infrastructure is kept up-to-date with latest stable patches and firmware.",["Patch network devices regularly","Track firmware versions","Test before deployment","Maintain update schedule"],["Patch records","Firmware inventory","Test results","Update schedule"],["Network device exploitation","Known vulnerabilities"],"high",{"nist_800_53":["SI-2"],"iso_27001":["A.8.8"]},["12.2","12.3"],["https://www.cisecurity.org/controls/v8"]),
ctrl("cis-16-1","CIS Controls v8","Application Software Security","CIS-16","16.1","Establish and Maintain a Secure Application Development Process","Establish and maintain a secure application development process.",["Implement SSDLC","Require security reviews","Conduct SAST/DAST","Train developers"],["SSDLC documentation","Review records","Scan results","Training records"],["Application vulnerabilities","Insecure code"],"high",{"nist_800_53":["SA-3","SA-11"],"iso_27001":["A.8.25"]},["16.2","16.12"],["https://www.cisecurity.org/controls/v8"]),
]

if __name__=="__main__":
    print("GRC Batch 5 — NIST + GDPR + CIS...")
    # NIST expanded 2
    data={"id":"nist-800-53-batch2","name":"NIST 800-53 Rev 5 (Batch 2)","description":"Additional NIST controls","controls":NIST5}
    with open(OUTPUT_DIR/"nist_800_53_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  NIST batch 2: {len(NIST5)}")
    # GDPR
    data={"id":"gdpr","name":"GDPR","description":"General Data Protection Regulation — Key Articles","controls":GDPR}
    with open(OUTPUT_DIR/"gdpr.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  GDPR: {len(GDPR)}")
    # CIS expanded
    data={"id":"cis-v8-batch2","name":"CIS Controls v8 (Batch 2)","description":"Additional CIS Controls","controls":CIS5}
    with open(OUTPUT_DIR/"cis_v8_batch2.json",'w') as f: json.dump(data,f,indent=2)
    print(f"  CIS batch 2: {len(CIS5)}")
    # Total
    total=0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            d=json.load(f)
            if isinstance(d,list): total+=len(d)
            elif "controls" in d: total+=len(d["controls"])
    print(f"\n  TOTAL CONTROLS: {total}")
