#!/usr/bin/env python3
"""Generate GRC quiz questions — scenario-based, theory, practical."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "questions"
OUTPUT_DIR.mkdir(exist_ok=True)

def q(id,topic,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

QS=[
# NIST (10)
q("gq-nist-01","nist","theory","medium","What are the six functions of NIST CSF 2.0?",["govern identify protect detect respond recover"],"contains_all",[],"NIST CSF 2.0 functions: Govern, Identify, Protect, Detect, Respond, Recover. Govern was added in version 2.0.",["Six functions, one is new in v2.0"]),
q("gq-nist-02","nist","theory","medium","What is the purpose of NIST 800-53?",["security controls","control catalog","federal","comprehensive controls"],"contains_any",[],"NIST 800-53 provides a comprehensive catalog of security and privacy controls for federal information systems and organizations.",["Comprehensive control catalog"]),
q("gq-nist-03","nist","scenario","hard","Your organization needs to comply with NIST 800-53 but has limited resources. How do you prioritize which controls to implement first?",["baseline","impact level","high","moderate","low","categorize"],"contains_any",[],"Use FIPS 199 to categorize systems by impact level (Low/Moderate/High), then select the corresponding control baseline. Start with High-impact systems.",["Categorize by impact first"]),
q("gq-nist-04","nist","theory","easy","What does the 'Identify' function in NIST CSF focus on?",["assets","risk","understand","inventory","business context"],"contains_any",[],"Identify: understand your assets, business environment, governance, risk assessment, and supply chain risks. You can't protect what you don't know about.",["Know what you have"]),
q("gq-nist-05","nist","scenario","hard","An auditor asks for evidence of your access control implementation (AC-2 Account Management). What documentation do you provide?",["account inventory","access review","provisioning","termination","approval"],"contains_any",[],"Provide: account inventory, access provisioning/approval records, periodic access reviews, termination checklists, and shared account justifications.",["Show the lifecycle of accounts"]),
# ISO 27001 (10)
q("gq-iso-01","iso27001","theory","medium","What is an ISMS?",["information security management system","systematic approach","manage","policies procedures"],"contains_any",[],"ISMS (Information Security Management System) is a systematic approach to managing sensitive information through policies, procedures, and controls.",["Systematic approach to security"]),
q("gq-iso-02","iso27001","theory","medium","What is the Plan-Do-Check-Act cycle in ISO 27001?",["plan do check act","pdca","continuous improvement","establish implement monitor improve"],"contains_any",[],"PDCA: Plan (establish ISMS), Do (implement), Check (monitor/review), Act (improve). Drives continuous improvement.",["Four-step cycle"]),
q("gq-iso-03","iso27001","scenario","hard","Your company wants ISO 27001 certification. What is the first step?",["scope","define scope","gap analysis","management commitment","context"],"contains_any",[],"First: define the ISMS scope (what's included), get management commitment, and conduct a gap analysis against ISO 27001 requirements.",["Define what's in and what's out"]),
q("gq-iso-04","iso27001","theory","hard","What is the Statement of Applicability (SoA) in ISO 27001?",["which controls","applicable","justification","selected controls","annex a"],"contains_any",[],"The SoA documents which Annex A controls are applicable, which are implemented, and justification for any exclusions. It's a key certification document.",["Which controls apply and why"]),
q("gq-iso-05","iso27001","theory","medium","How many controls are in ISO 27001:2022 Annex A?",["93","93 controls"],"contains_any",[],"ISO 27001:2022 has 93 controls in Annex A (reduced from 114 in 2013 version), organized into 4 themes: Organizational, People, Physical, Technological.",["Less than 100, organized in 4 themes"]),
# Risk Management (10)
q("gq-risk-01","risk","theory","easy","What is the risk formula?",["likelihood times impact","likelihood x impact","probability x impact","likelihood * impact"],"contains_any",[],"Risk = Likelihood × Impact. A high-likelihood, high-impact event is critical. Low-likelihood, low-impact is acceptable.",["Two factors multiplied"]),
q("gq-risk-02","risk","theory","medium","What are the four risk treatment options?",["mitigate transfer accept avoid","reduce transfer accept avoid","treat","accept","transfer","avoid"],"contains_any",[],"Four options: Mitigate (reduce risk), Transfer (insurance/outsource), Accept (acknowledge and monitor), Avoid (eliminate the activity).",["Four choices for each risk"]),
q("gq-risk-03","risk","scenario","hard","Your risk assessment shows a critical risk of ransomware. The board asks for options. What do you present?",["mitigate","backup","insurance","controls","accept"],"contains_any",[],"Present: Mitigate (backups, EDR, patching, training), Transfer (cyber insurance), Accept (document residual risk). Avoid is impractical for most organizations.",["Multiple treatment options for the board"]),
q("gq-risk-04","risk","theory","medium","What is residual risk?",["remaining risk","after controls","risk that remains","leftover"],"contains_any",[],"Residual risk is the risk remaining after controls are applied. No control eliminates risk completely. Residual risk must be formally accepted by management.",["What's left after you apply controls"]),
q("gq-risk-05","risk","scenario","hard","A department head says 'we accept the risk' of not encrypting laptops. What governance process should follow?",["document","sign","risk register","formal acceptance","management approval","review"],"contains_any",[],"Formal risk acceptance requires: documented justification, appropriate authority level (not just the department head), entry in risk register, periodic review, and sign-off.",["Formal process, not just verbal"]),
# Compliance (10)
q("gq-comp-01","compliance","theory","medium","What is the maximum GDPR fine?",["4%","4% of revenue","20 million","whichever is greater"],"contains_any",[],"GDPR maximum fine: €20 million or 4% of global annual revenue, whichever is greater.",["Percentage of revenue"]),
q("gq-comp-02","compliance","theory","medium","What is the GDPR right to erasure?",["delete data","right to be forgotten","remove personal data","erasure"],"contains_any",[],"Right to erasure (right to be forgotten): data subjects can request deletion of their personal data when it's no longer necessary or consent is withdrawn.",["Delete my data"]),
q("gq-comp-03","compliance","scenario","hard","A customer requests all their personal data under GDPR Article 15. What is your response deadline?",["30 days","one month","without undue delay"],"contains_any",[],"Respond within 30 days (one month). Can extend by 2 months for complex requests, but must inform the requester within the first 30 days.",["One month"]),
q("gq-comp-04","compliance","theory","medium","What does PCI DSS protect?",["cardholder data","payment card","credit card","card data"],"contains_any",[],"PCI DSS protects cardholder data (card numbers, expiry, CVV) and sensitive authentication data during storage, processing, and transmission.",["Payment card information"]),
q("gq-comp-05","compliance","scenario","hard","Your company processes credit cards and suffers a breach. Under PCI DSS, what must happen within 72 hours?",["notify","report","acquirer","card brand","forensic investigation"],"contains_any",[],"Notify your acquiring bank and card brands within 72 hours. Engage a PCI Forensic Investigator (PFI). Contain the breach and preserve evidence.",["Notify payment partners quickly"]),
q("gq-comp-06","compliance","theory","medium","What is HIPAA and what does it protect?",["health information","phi","protected health information","healthcare","patient data"],"contains_any",[],"HIPAA protects Protected Health Information (PHI) — any individually identifiable health information held by covered entities and business associates.",["Patient health data"]),
q("gq-comp-07","compliance","theory","hard","What is the difference between a data controller and a data processor under GDPR?",["determines purpose","processes on behalf","controller decides","processor acts on instructions"],"contains_any",[],"Controller determines WHY and HOW data is processed (makes decisions). Processor processes data ON BEHALF of the controller (follows instructions).",["One decides, one executes"]),
q("gq-comp-08","compliance","scenario","hard","Your SaaS vendor stores customer data in the EU but wants to move to US servers. What GDPR mechanism is needed?",["standard contractual clauses","scc","adequacy","transfer impact assessment","schrems"],"contains_any",[],"Need Standard Contractual Clauses (SCCs) or other transfer mechanism since the US lacks an adequacy decision. Conduct a Transfer Impact Assessment (TIA).",["Legal mechanism for international transfer"]),
# Audit (5)
q("gq-audit-01","audit","theory","medium","What is the difference between an internal and external audit?",["internal self","external independent","first party","third party"],"contains_any",[],"Internal audit: conducted by the organization itself (first party). External audit: conducted by independent third party (certification body, regulator).",["Self vs independent"]),
q("gq-audit-02","audit","theory","medium","What are the three types of audit findings?",["nonconformity","observation","opportunity","major","minor"],"contains_any",[],"Major nonconformity (critical gap), Minor nonconformity (partial gap), Observation/Opportunity for Improvement (suggestion, not a failure).",["Severity levels of findings"]),
q("gq-audit-03","audit","scenario","hard","During an ISO 27001 audit, the auditor finds you have no evidence of management review meetings. What severity is this finding?",["major nonconformity","major","critical"],"contains_any",[],"Major nonconformity — management review is a mandatory ISO 27001 requirement (Clause 9.3). Missing it entirely indicates a systemic ISMS failure.",["Mandatory requirement completely missing"]),
q("gq-audit-04","audit","theory","medium","What is audit evidence?",["records","documents","observations","proof","logs","screenshots"],"contains_any",[],"Audit evidence: records, documents, logs, screenshots, interview notes, and observations that prove controls are implemented and effective.",["Proof that controls work"]),
q("gq-audit-05","audit","scenario","hard","An auditor asks 'show me evidence that access reviews are performed quarterly.' What do you provide?",["review records","screenshots","sign-off","dates","quarterly reports","access review reports"],"contains_any",[],"Provide: dated access review reports/screenshots, reviewer sign-offs, remediation records for revoked access, and evidence of quarterly cadence.",["Dated proof of regular reviews"]),
]

if __name__ == "__main__":
    with open(OUTPUT_DIR / "grc_quiz.json", 'w') as f:
        json.dump(QS, f, indent=2)
    print(f"Generated {len(QS)} GRC questions")
